### ISSUE TITLE
Create better strategy for storing content on filesystem

### ISSUE THREAD

**Issue by bilak** [paulcwarren/spring-content#1]
Current FS implementation stores contents in one directory. This will lead to performance issue/bottleneck because (from my experiences) storing more than 10000 contents to one directory doesn't have good impact on FS/OS.

This could help:
Instead of working with UUID, just persist entity with Long/Integer etc... what will autoincrement the sequence. Then hash (hex) this number. For instance if the path of store could be something like /XX/XX/XX/ZZZ.extension then potentially there could be 16760438784 contents in one store (if I counted it correctly). XX is in range 0-255 (256), ZZZ is range 1-999 (999 if we don't start with number 0).

If I can help somehow with pull request let me know, but I'm just reading codebase so it can take some time to understand it.

**Comment by Oskoss** [comment]
Hi @bilak,

You are exactly on point with this issue, @paulcwarren and I both spoke about this awhile back. I created a story for us to take a look next week. Depending on the outcome a PR might be just what we need!

Have a great weekend!

**Comment by paulcwarren** [comment]
Hi Lukas,
We think we know how we should achieve this.  

We probably want to add a `PlacementStrategy` bean with a `getLocation` method that, given an ID, returns a `path` (probably a String, but maybe a URI?).  

This `path` can then be used with an expanded `ResourceTemplate` service (currently `AbstractResourceTemplate`) that exposes Spring `Resource` objects and their streams.

`DefaultXYZRepositoryImpl`'s can use this `PlacementStrategy` bean together with the `ResourceTemplate` to implement their `ContentStore` functionality.  I imagine at least SC FS and SC S3 will want to make use of this.  We need to look into Mongo's GridFS - it may well be capable of support this too.  On the flip-side it doesn't make any sense for SC JPA.     

The other reason for creating an expanded `ResourceTemplate` (and for keeping the placement strategy separate from it) is to enable application's that don't want full CM functionality to also do content access (in the same developer friendly way) thus increasing the appeal of Spring Content.

**Comment by bilak** [comment]
Hi Paul,

interesting ideas. I don't know much about S3 and Mongo but I've got another ideas for FS. From current implementation it looks like when I want new FS content store (CS) then I need to create new entity/spring repository/content repository for it. There could be an option where all contents will be stored in one entity/content store and somehow partitioned. Let's create annotation `@FileSystemPartition` (or maybe some name which fits better) for entity field which will split contents in partitions on FS (e.g. /filesystemroot/partition1 /filesystemroot/partition2). For this there also need to be some `@ContentId` generator which will guarantee the correct "sequence" id generation.

```
interface PartitionContentIdGenerator {
   Object generateIdForPartition(Object partition);
}
```
Maybe parameter and return type should be of Long type.

I was working on something similar today, but was interrupted by other project. If I have time during next days I will try to create some branch and post my ideas.

**Comment by paulcwarren** [comment]
Atm the root of the content store is configured globally but I think you are right it should be configurable on a per content repository basis and that could very well be done via an annotation on the content repository interface, or something like that.  Sounds like a different issue to me though so I created [this issue](https://github.com/paulcwarren/spring-content/issues/5) to keep it separate from from this placement strategies one.

**Comment by bilak** [comment]
Hi guys, 
try to look at [this](https://github.com/bilak/spring-content/commit/575945561ac239b1e73c1c72b581f6df39707360) commit and tell me what do you think about it. It isn't finished yet, but I want to listen from you if that could be way how the FS can perform. I must implement somehow the configuration for [SimplePartitionDefinition](https://github.com/bilak/spring-content/blob/575945561ac239b1e73c1c72b581f6df39707360/spring-content-fs/src/main/java/internal/org/springframework/content/fs/operations/partition/SimplePartitionDefinition.java) or generally for [PartitionDefinition](https://github.com/bilak/spring-content/blob/575945561ac239b1e73c1c72b581f6df39707360/spring-content-fs/src/main/java/internal/org/springframework/content/fs/operations/partition/PartitionDefinition.java) and I'm thinking about DB config or application.yml config. What do you think?

**Comment by paulcwarren** [comment]
@bilak we have implemented a pluggable storage strategy with a UUID-based implementation for SC Filesystem and SC S3.  We believe this will resolve this issue for you.

You can find more information in the [filesystem docs](https://paulcwarren.github.io/spring-content/refs/current/fs-index.html).  See 3.3.1. Storage Model.
