### ISSUE TITLE
Upgrade spring-content-jpa to Spring Data 2 (Hibernate 5.2)

### ISSUE THREAD

**Issue by heruan** [paulcwarren/spring-content#10]
Hibernate 5.2 contains many improvements and some breaking changes from 5.0 and Spring Data 2 depends on it.

It would be great to have a branch with support for Hibernate 5.2 and prepare for Spring Data 2 release!

**Comment by paulcwarren** [comment]
@heruan thanks for the input.  We'll add this to the backlog and have a look soonest.

**Comment by paulcwarren** [comment]
I see.  Master branch of spring-data-jpa is built against 5hibernate 5.2.10.Final libraries.  I assume what is on 'master' is Spring Data 2?  We can take a look at upgrade to that.

**Comment by paulcwarren** [comment]
Fixed with release `0.1.0` that updates Spring Boot dependency to `2.0.2` that pulls in Hibernate `5.2.17`.

Let me know if you find any issues.
