### ISSUE TITLE
Lock versioning

### ISSUE THREAD

**Issue by repantoja** [paulcwarren/spring-content#1000]
Hi Paul,
I am having an issue when I am trying to lock the record. I am using x509 to authenticate, the user, so when the lock function gets call my authentication is getting the certificate cn which is 78 character long but the locks db only allows 64 characters is there a way to override the lock function or the locks schema?

**Comment by paulcwarren** [comment]
Hi @repantoja ,

We follow database initialization patterns used elsewhere in Spring.  So, you cant configure the length of that column per se but you can override the sql used to initialize the database.  

If you are using Spring Boot then you would do this by overriding the `spring.versions.jpa.schema` property and pointing it at your .sql file on your classpath.  The default is [here](https://github.com/paulcwarren/spring-content/blob/28a72c6a23e811f2e6430f4dd3a8c8b25b0d6ddc/spring-content-autoconfigure/src/main/java/internal/org/springframework/versions/jpa/boot/autoconfigure/JpaVersionsProperties.java#L9).

Or if you are not using Spring Boot then you are (presumably) already intializing the database yourself like [this](https://github.com/paulcwarren/spring-content-examples/blob/65f998914b060e0cf17cc4257ca7380869eb37c7/spring-eg-versions-jpa/src/test/java/examples/H2TestConfig.java#L86) and you can, again, specify the sql you want to use to init the db.  

Both approaches will allow you to change the length of the lock_owner column to suit your needs.

HTH

**Comment by repantoja** [comment]
Hi Paul,
Thank you for your reply I tried adding spring.versions.jpa.schema=locks_schema.sql on my property file, but I keep getting the following error:
No setter found for property: schema
thanks for your help

**Comment by paulcwarren** [comment]
Ah! Right.  There is no setter on that property.  I didnt spot that.  Sorry about that.

Well, database initialization is based on classpath resources so, I think, you can override the underlying .sql file by specify your own at the same classpath.  i.e. 

Create `./src/main/resources/org/springframework/versions/jpa/schema-<your db>.sql` with:

```
CREATE TABLE IF NOT EXISTS locks(
    entity_id VARCHAR(64) NOT NULL PRIMARY KEY,
    lock_owner VARCHAR(78)
);
CREATE UNIQUE INDEX IF NOT EXISTS locks_pk ON locks(entity_id, lock_owner);
````

where your-db is something like `h2` or `postgres` or whatever.  I can try and confirm what that is if you let me know which db you are using.

**Comment by repantoja** [comment]
I am using mysql thanks for your help

**Comment by paulcwarren** [comment]
So, I think the file you want to create to override the provided one would be:

`./src/main/resources/org/springframework/versions/jpa/schema-.sql`

Your overriding this provided [one](https://github.com/paulcwarren/spring-content/blob/28a72c6a23e811f2e6430f4dd3a8c8b25b0d6ddc/spring-versions-jpa/src/main/resources/org/springframework/versions/jpa/schema-mysql.sql) so, use that as a basis and update the field length as necessary.

I believe that should work for you.

**Comment by paulcwarren** [comment]
Hi @repantoja, did that work for you?

**Comment by repantoja** [comment]
HI Paul I am sorry I was out of the office and I haven't implement the changes yet.

**Comment by paulcwarren** [comment]
No problem.  I was just checking in.

**Comment by repantoja** [comment]
Hi Paul I was able to fix it by implementing your answer thank you for your help.

**Comment by paulcwarren** [comment]
Great.  Glad I was able to help.

**Comment by rhhaley** [comment]
This problem doesn't address the issues with two models that each have one item with an entity_id of "1" and you wan to lock each of them separately.

the lock table doesn't allow locks on both but there is no error?
