### ISSUE TITLE
spring-content-cmis CMIS Compliance (TCK fails)

### ISSUE THREAD

**Issue by tomas-pritrsky** [paulcwarren/spring-content#1073]
CMIS Workbench TCK test fails when running it against spring-content.
I consider the TCK test tell if the server is CMIS compliant or not. 

**To Reproduce**
1. follow the tutorial at https://paulcwarren.github.io/spring-content/spring-content-with-cmis-docs/
2. start server
3. start CMIS Workbench (I'm using version 1.2.0)
4. run TCK
5. it shows plenty of failures, mostly 'property missing'

**Expected behavior**
TCK test passes without errors and spring-content-cmis actually makes the content store CMIS compliant.

**Screenshots**
![image](https://user-images.githubusercontent.com/15112401/190220332-858958a8-1fb3-4776-a878-f07a91adfcbc.png)
![image](https://user-images.githubusercontent.com/15112401/190220434-5e1c160b-6d09-438f-af17-b6e1c1474133.png)

Thank you.

**Comment by paulcwarren** [comment]
Thanks @tomaspritrsky, atm I consider the cmis module alpha.  And you are right I never took the time to make the `tck` pass.  But probably should.  

I can spend a bit of time looking into this to see how much effort is involved but would love some help getting there, if possible.

**Comment by tomas-pritrsky** [comment]
I managed to fix the cmis:description (contained in 47 TCK errors), but I can't push it here. There are more properties to be fixed though, but I didn't figure it out.
TODO: 
cmis:secondaryObjectTypeIds
cmis:creationDate
cmis:lastModificationDate
cmis:changeToken
cmis:allowedChildObjectTypeIds

cmis:description fix
![image](https://user-images.githubusercontent.com/15112401/190469251-e6bee721-e4ea-4881-bbf0-2ef05cbc0851.png)

**Comment by paulcwarren** [comment]
Great.  That's awesome and super helpful.

Can't push?  Are you trying to push to branch?  Or did you fork?

**Comment by tomas-pritrsky** [comment]
I didn't fork, just pulled this repo and am now trying to push a branch here, it says I don't have write access :) I don't know, never contributed to project on github before :(

**Comment by paulcwarren** [comment]
The way it works is you create fork (using the button top-left) and you commit and push to that.  Then create a PR back to this repository.

So I would:
- `git stash` your changes
- create a fork of the main branch of this repo in your github org
- `git stash pop` your changes
- `git commit -m "<you message>"`
- `git push`
- create PR

**Comment by tomas-pritrsky** [comment]
thanks, see #https://github.com/paulcwarren/spring-content/pull/1076
I hope somebody can help with the other CMIS properties.

**Comment by paulcwarren** [comment]
Thanks for the PR @tomas-pritrsky.  Looks good.  Merged.  

I can help you resolve the other issues but it is going to take me a minute to get back set up with the cmis stuff.  I'll do my best.

**Comment by tomas-pritrsky** [comment]
no problem @paulcwarren . Your help would be much appreciated. I tried other open-source DMS servers which say support CMIS, but I found they don't support it 100% (TCK failed on all of them... more or less). So, I might just as well stick to your solution and improve on it.

**Comment by paulcwarren** [comment]
Hi @tomas-pritrsky, 

I discovered a rather large and intractable problem with the cmis module whilst upgrading to Spring Boot 3.  SB3/SF6 requires Java 17 and the apache chemistry library (that provides a lot of the heavy lifting by providing the CMIS Rest API) no longer works on that version of Java.  Moreover, with the last release being 7 years ago I am not hopeful that the existing maintainers will address this anytime soon.  It might be worth raising an issue to test that theory though?

Sadly, I just do not have the bandwidth to adopt this rest layer either.   So, there is an opportunity there for someone to take that on and become a committer on the project.  I have asked a few of the larger existing Spring Content users if they would be interested but none of them are as they all view CMIS as basically dead at this point.  

So, as it stands the CMIS module is not present in the Spring Content 3.   Apologies for any inconvenience that this causes.

**Comment by paulcwarren** [comment]
I'm going to go ahead and cause the associated PRs.  Just FYI.

**Comment by paulcwarren** [comment]
Closing "wont fix" due to the apache chemistry project expiring out on us
