### ISSUE TITLE
Filesystem root property

### ISSUE THREAD

**Issue by heruan** [paulcwarren/spring-content#11]
Does the `spring.content.fs.filesystemRoot` property actually work? I set it to `/media/content` (a directory which exists on the filesystem) but it's not used at all. Am I doing something wrong?

**Comment by heruan** [comment]
It does work without the `spring` prefix, i.e. just `content.fs.filesystemRoot`, but [documentation](https://paulcwarren.github.io/spring-content/refs/release/fs-index.html) states:

> ## 3.2. Configuring
> The following configuration properties (prefix spring.content.fs) are supported.
> 
> Property | Description
> -- | --
> filesystemRoot | content store location (defaults to java.io.tmpdir/<random>/.

It would be great to have it actually under `spring`, which is the prefix most Spring libraries are converging to.

**Comment by paulcwarren** [comment]
I agree.  in fact it was originally `spring.content.fs.filesystemRoot` but we changed it to just `content.fs.filesystemRoot` in a more generally renaming effort to try and get our 'starters' added to the Spring Boots Starters readme.  However, that wasn't successful..so I am happy change this back.

**Comment by paulcwarren** [comment]
Fixed 0.0.8

**Comment by harshalpatil2012** [comment]
Hi Paul where to define content.fs.filesystemRoot. I want to set custom file path  in spring boot project to store video.

**Comment by paulcwarren** [comment]
The property is actually `spring.content.fs.filesystemRoot`.  In a Spring Boot-based application you can define it in a number of places actually.  According to [this](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding) you could put `spring.content.fs.filesystemRoot` or `spring.content.fs.filesystem-root` or `spring.content.fs.filesystem_root` in your application.properties/yaml.  Or you could set `SPRING_CONTENT_FS_FILESYSTEMROOT` as an environment variable that you application runs with (which is what you usually do when running it in Kubernetes or Cloudfoundry for example).  Let me know if this doesn't work for you.

**Comment by harshalpatil2012** [comment]
Hey Paul thanks so much for the reply.
Also is it possible to change this root path dynamically at runtime?

**Comment by paulcwarren** [comment]
Unfortunately, Spring Content Filesystem does not support this currently.  Spring Content S3 does though.  There are actually three ways to do it depending on what you need to achieve.  You can create a `Store` based on an `S3ObjectId` SID.  Alternatively, you can also configure your S3 Storage with a `S3ObjectIdResolver`.  If you are using Spring Data and associating content with Entity's then you can annotate one of your Entity's field with `@Bucket`.  All of these strategies help Spring Content decide the bucket at runtime.  You can read more about it [here](https://paulcwarren.github.io/spring-content/refs/release/s3-index.html) - Section 2.3.

If you don't want to use S3 then we can absolutely add a similar feature to Filesystem.  Feel free to create a PR, or raise a dedicated issue for it.  We are just finishing up the release 0.1.0 (Spring Boot 2) and then we would be able to pick that up for you.
