### ISSUE TITLE
Links to content properties are truncated at first uppercase letter

### ISSUE THREAD

**Issue by vierbergenlars** [paulcwarren/spring-content#1146]
**Describe the bug**

We have JPA-entity with a spring-content annotated property.

```java
@Entity
@NoArgsConstructor
@Getter
@Setter
public class AnEntity {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private UUID id;

	private String attributeOne;

	@ContentId
	private String someDataId;

	@ContentLength
	private long someDataLength;

	@MimeType
	private String someDataMimetype;

	@OriginalFileName
	private String someDataFilename;
}
```

Between version `2.4.0` and `2.5.0`, the content URL for this property has changed from `http://localhost:8889/anEntities/dbbb7979-e2ab-4e92-be4a-5e7727381650/someData` to `http://localhost:8889/anEntities/dbbb7979-e2ab-4e92-be4a-5e7727381650/some`

**Expected behavior**

The content URL matches the (virtual) property name, instead of only the first part before an uppercase letter.

**Comment by paulcwarren** [comment]
Thanks @vierbergenlars.  Will look into this.
