### ISSUE TITLE
Fields in superclass are not set

### ISSUE THREAD

**Issue by heruan** [paulcwarren/spring-content#12]
Seems like `BeanUtils.getFieldWithAnnotation` and `BeanUtils.setFieldWithAnnotation` do not search for annotated fields in superclasses, thus limiting the use of inheritance.

**Comment by paulcwarren** [comment]
This looks good.  I'll add some tests this morning for coverage and accept this PR.  Thanks very much @heruan

**Comment by heruan** [comment]
Great! I don't use annotated getters so I don't know if the `PropertyDescriptor` method you use to get annotated getters should be fixed to include inherited getters or it already does.

**Comment by heruan** [comment]
Any ETA for a release with this fix?

**Comment by paulcwarren** [comment]
Hi @heruan, we apologize.  We have been out attending conferences.  If I recall this has been done so perhaps we'll just cut a release this week so you can grab it.

**Comment by paulcwarren** [comment]
Fixed in 0.0.7
