### ISSUE TITLE
Startup with MongoStore enabled and S3Client bean also available fails with missing class

### ISSUE THREAD

**Issue by shuston** [paulcwarren/spring-content#1260]
**Describe the bug**
I have an application that uses Mongo Content Store to save content in MongoDB/GridFS. All great, works wonderful. Then I added a separate capability to the app that can store things in S3, totally unrelated to use of Spring Content. That capability configures an S3Client bean. Now when I start the app I get an exception:

```org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.collins.railwaynet.ris.RisMainApplication]; nested exception is java.io.FileNotFoundException: class path resource [internal/org/springframework/content/s3/config/S3StoreConfiguration.class] cannot be opened because it does not exist```

**To Reproduce**
1. Run executable jar with application
2. See error

**Expected behavior**
Hoping Spring Content will see that there is no S3StoreConfiguration but there is a MongoStore configured, ignore the S3Client, and continue. Alternately, provide a property that can instruct Spring Content to only use Mongo.

**Additional context**
I am using version 2.7.0 with this Maven dependency:
```		<dependency>
		    <groupId>com.github.paulcwarren</groupId>
		    <artifactId>spring-content-mongo-boot-starter</artifactId>
		</dependency>
```

**Comment by paulcwarren** [comment]
Thanks for the report @shuston.  Yeah, autoconfigurations are all a single module (`spring-content-autoconfigure`) and therefore using any spring boot starter pulls them all in.  It sounds like the autoconfiguration for s3 things is a little too aggressive here - essentially conditional on S3Client and nothing else.  I'll take a look and see if we can make a little less so.  Making it conditional on a class from the s3 module might work as you suggest.

**Comment by shuston** [comment]
A workaround (for me, at least) is to provide a `spring.content.storage.type.default` property with value `gridfs` - this avoids the attempt to configure S3.

**Comment by paulcwarren** [comment]
Hey @shuston there is a potential fix for this on both 2.9.0-SNAPSHOT and 3.0.2-SNAPSHOT.  I validated my end using a setup that I think would reproduce the issue but be great if you can verify too.  No worries if not I'll cut new releases shortly.

**Comment by paulcwarren** [comment]
Hi @shuston, from the error I am guessing you are on windows.  I wouldn't expect that to work as all dev is done on macs.  

That said you don't need to build it yourself.  You just need to (temporarily) update you pom or gradle file to depend on the latest SNAPSHOT verison rather than the release version.  Baeldung describes how to do that for a maven project [here](https://www.baeldung.com/maven-snapshot-release-repository#1-deploy-an-artifact).

Spring Content snapshots are host on `https://oss.sonatype.org/content/repositories/snapshots`

**Comment by paulcwarren** [comment]
Great.  Thanks @shuston.  I'll cut a release soonest.  Many thanks.
