### ISSUE TITLE
REST content request gives 404 when using spring.data.rest.base-path

### ISSUE THREAD

**Issue by Nick-Wunderdog** [paulcwarren/spring-content#1373]
**Describe the bug**
I followed the code in https://paulcwarren.github.io/spring-content/spring-content-rest-docs/
Only difference is that I am using 
`spring.data.rest.base-path= /api `
So that Spring Data REST (SDR) is exposed from context "/api", which the @StoreRestResource does not seem to abide to. 
Can GET the related JPA Entity by ID ok. But when trying to PUT the binary data I get 404. Also trying to GET the previously added data (when app was running without  data.rest.base-path property) gives 404. 

SB application MUST run at "/" as it serves React Frontend from root context and only the REST needs to be in "/api" context. Spring Data REST supports this nicely. It seems that StoreRestResource is not following the convention and behavior of spring RestResource on `spring.data.rest.base-path` . 

[edit]
But is seems to be working without the base path. 
as SDR gives me the Entity from : GET /api/attachments/102
the expected GET /api/attachments/102/content is not working, but URL works without the REST base path 
GET /attachments/102/content. 

So it is a bit inconsistent with behavior of SDR.  

**Expected behavior**
For `@StoreRestResource` to abide and use `spring.data.rest.base-path`  property value. 

**Screenshots**
N/A

**Additional context**
removing the `data.rest.base-path`  property, the StoreRestResource works ok. Both PUT the binary and GET it.

**Comment by Nick-Wunderdog** [comment]
Digging up more on this @paulcwarren said in 2017 that this functionality should be coming to version 0.0.7
   https://github.com/paulcwarren/spring-content/issues/9
   
I am using yaml properties file, coudl that be the issue of `@StoreRestResource` not abiding the `spring.data.rest.base-path` property ?

**Comment by paulcwarren** [comment]
@Nick-Wunderdog thanks for giving Spring Content a go.  Spring Content does not pay attention to spring data properties.  The Spring Content property for setting the base-path described [here](https://paulcwarren.github.io/spring-content/refs/snapshot/main/rest-index.html#_changing_the_base_uri)

**Comment by Nick-Wunderdog** [comment]
Thank you very much. It was clearly documented and I managed to miss it.

**Comment by Nick-Wunderdog** [comment]
FYI, my solution was: 
```yaml
spring:
  data:
    rest:
      base-path: /api

  content:
    rest:
      baseUri: ${spring.data.rest.base-path}
```
