### ISSUE TITLE
Is there a pre get content resource handler?

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#140]
before user access content resource , I have to append the resource (PDF file) with a watermark , using current username, is there have any way to do that?

**Comment by lmtoo** [comment]
Or custom the resource's link ,to add a watermark link, and disable the default link

**Comment by paulcwarren** [comment]
What is the content-type of the original content @lmtoo ?  

If it isn't already PDF then you could register a renderer that converts content to "application/pdf" - the content type of your watermarked content.  

In this renderer, you can get the current thread's security context and from that the principal (i.e. username) and then do your watermarking logic to generate the content with the watermark.

On the client, if you then make a GET request to the original content's URI but specify an accept header with content-type "application/pdf" the store rest controller will invoke your renderer and return the content it generates

**Comment by lmtoo** [comment]
The original content is already PDF ,I implement a renderer  from "application/pdf" to "application/pdf", but it's not work correctly

**Comment by paulcwarren** [comment]
I see.  Let me take a look at that for you.  Thanks @lmtoo

**Comment by paulcwarren** [comment]
When there are renderers that produce content matching the original content-type, the StoreRestController gave precedence to the original content over the renderers.  This [commit](b082c22368da6587abf14f89cb6b6cc3d2a5dcb6) fixes that.
