### ISSUE TITLE
Circular references in `AzureStorageConfiguration` during application startup

### ISSUE THREAD

**Issue by claudia-maderthaner-infoniqa** [paulcwarren/spring-content#1431]
**Describe the bug**
The `AzureStorageConfiguration` bean may cause an exception during application startup due to circular references. This seems to be connected the bean provider for the `PlacementService` in this class.

**To Reproduce**
We noticed this problem during the migration of an existing project to Spring Boot 3.

Test Environment:
Windows 11
Java 17
Spring Boot v3.0.6
Spring Content v3.0.3

**Expected behavior**
The `AzureStorageConfiguration` bean should be created without error.

**Additional context**
The problem only happens with the Spring Content Azure Storage module. The Spring Content S3 module is working.

We were able to make a fix for the issue by refactoring the provider for the `PlacementService` (by using the same object creation strategy as in the `S3StoreConfiguration` in the Spring Content S3 module).

**Comment by paulcwarren** [comment]
Thanks so much @claudia-maderthaner-infoniqa
