### ISSUE TITLE
redirect cloud storage service's public url

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#145]
hi, @paulcwarren . I develop a module by followe spring-content-fs to integrate a third cloud storage service, and the storage service privide a public url to get the file,  but customer access content must through spring-content app , I think when customer access content , return 304 redirect to this public url will lower network load

**Comment by paulcwarren** [comment]
Hi @lmtoo I think you can use the same approach that we talked about in [another issue you raised](https://github.com/paulcwarren/spring-content/issues/85#issuecomment-585304231); i.e. create your own controller that handles content GET requests.   As this will be in front of the Spring Content StoreRestResource controller and will get called first you can return the 304 redirect.

Would that work?
