### ISSUE TITLE
S3ContentStore, FilesystemContentStore, etc extend deprecated ContentStore

### ISSUE THREAD

**Issue by jacobbroberg** [paulcwarren/spring-content#1458]
**Describe the bug**
When [migrating to Spring Boot 3](https://github.com/paulcwarren/spring-content/commit/3c11eda2898910bcbc4eb8c99f7c67693ccd8c0d), the `org.springframework.content.commons.repository.ContentStore` was marked as deprecated and moved to `org.springframework.content.commons.store.ContentStore`.

But the specific interface extensions of `ContentStore`, e.g. [`S3ContentStore`](https://github.com/paulcwarren/spring-content/blob/main/spring-content-s3/src/main/java/org/springframework/content/s3/store/S3ContentStore.java) and [`FilesystemContentStore`](https://github.com/paulcwarren/spring-content/blob/main/spring-content-fs/src/main/java/org/springframework/content/fs/store/FilesystemContentStore.java) still use the old `ContentStore` and therefore generate a lot of deprecation warnings.

**To Reproduce**
I use Spring Boot 3.1.0 and `spring-content-fs-boot-starter` and `spring-content-s3-boot-starter` version 3.0.3.
Warnings show up in Eclipse IDE.

**Expected behavior**
All interface extensions of `ContentStore` should be refactored to use the new/moved [`ContentStore`](https://github.com/paulcwarren/spring-content/blob/main/spring-content-commons/src/main/java/org/springframework/content/commons/store/ContentStore.java)

**Screenshots**
![image](https://github.com/paulcwarren/spring-content/assets/8348616/43c14f61-da7b-4ad5-9a19-a03c5da15a7e)

**Comment by jacobbroberg** [comment]
I can see that you write in the [3.0.0 release note](https://github.com/paulcwarren/spring-content/releases/tag/3.0.0) that _Package org/springframework/content/commons/repository/** has been deprecated and is scheduled for removal in Spring Content 4.x. Package org/springframework/content/commons/store/** replaces it._

But it would still be nice if the `S3ContentStore` and `FilesystemContentStore` among others could use the new package.

**Comment by paulcwarren** [comment]
Hey @jacobbroberg , ah yes.  The storage specific stores should indeed inherit from the new package.  Thanks.
