### ISSUE TITLE
Example app spring-content-rest showing deprecated controller

### ISSUE THREAD

**Issue by scanlonjts** [paulcwarren/spring-content#15]
@ContentStoreRestResource is being shown as deprecated
Is there something else we should be using?

**Comment by paulcwarren** [comment]
Hi @scanlonjts.  You should switch over, when convenient, to `StoreRestResource`.

Over a period of time we are making we are making the ContentStore API more generic by introducing a Store and an AssociativeStore underneath ContentStore.  As a result we also decided to rename ContentStoreRestResource -> StoreRestResource.  ContentStore will remain as we believe it is still useful.  But eventually @ContentStoreResourceResource will be removed.

**Comment by scanlonjts** [comment]
Thanks paul

**Comment by paulcwarren** [comment]
Welcome.  Closing.
