### ISSUE TITLE
Exception with unsetContent using SB3 and SC3.0.4 JPA Starter

### ISSUE THREAD

**Issue by andye2004** [paulcwarren/spring-content#1548]
**Describe the bug**
Can't unset content using spring-content-jpa-boot-starter as the `DefaultJpaStoreImpl.unassociate()` method is checking for javax `@Id` and not checking jakarta.

**To Reproduce**
create a JPA entity, set some content and save, then try to unset the content.

**Expected behavior**
The operation should succeed

**Comment by paulcwarren** [comment]
Many thanks for the fix.
