### ISSUE TITLE
File download not working on windows platform

### ISSUE THREAD

**Issue by planzonevi** [paulcwarren/spring-content#1556]
Hello

The following line will cause an IllegalArgumentException when trying to download files from Windows platform. 

https://github.com/paulcwarren/spring-content/blob/cec78cc2cd69cf095815353bb28ad08cd1e1d5d0/spring-content-rest/src/main/java/internal/org/springframework/content/rest/io/AssociatedStoreResourceImpl.java#L196

Windows uses windows-1252 as default charset which is not compliant to rfc 5987
I suggest to force UTF-8 or ISO-8859-1

Regards

**Comment by paulcwarren** [comment]
Thanks @planzonevi ,  I'll look into this as soon as I can
