### ISSUE TITLE
How do I configure com.github.paulcwarren:spring-content-bom for spring boot kotlin gradle? 

### ISSUE THREAD

**Issue by ddxl123** [paulcwarren/spring-content#1564]
How do I configure com.github.paulcwarren:spring-content-bom for spring boot kotlin gradle? 
Where can I check the latest version?

**Comment by paulcwarren** [comment]
Hi @ddxl123 , I am not a gradle expert.  I was expecting gradle users to be able to do this:

```
dependencies {
    implementation(enforcedPlatform("com.github.paulcwarren:spring-content-bom:3.0.0"))
    // Your other dependencies
}
``` 

And that does not work?
