### ISSUE TITLE
How to download a file from a content store

### ISSUE THREAD

**Issue by estebes** [paulcwarren/spring-content#16]
When i try to download a file from the server onto the disk i get an error saying server problem and in the server log i get "java.lang.UnsupportedOperationException: null
"

**Comment by paulcwarren** [comment]
@estebes is there anymore stack trace than that?  What Spring Content Module(s) are you using? Spring Content for JPA?  And are you also using Spring Content REST?

A small project that reproduces this issue would be very helpful as well.

You could also cross reference your project against the relevant example in github.com/paulcwarren/spring-content-examples

**Comment by estebes** [comment]
Full log - https://pastebin.com/1rtRt1QR

Dependencies 
`//  Spring Content >>
    /* https://mvnrepository.com/artifact/com.github.paulcwarren/spring-content-fs-boot-starter */
    compile group: 'com.github.paulcwarren', name: 'spring-content-fs-boot-starter', version: '0.0.7-SNAPSHOT'
    /* https://mvnrepository.com/artifact/com.github.paulcwarren/spring-content-rest-boot-starter */
    compile group: 'com.github.paulcwarren', name: 'spring-content-rest-boot-starter', version: '0.0.7-SNAPSHOT'
    // << Spring Content
`

Html code
`<a href="file.pdf" download>download here</a>`
This also happens when i open the content in a new tab and click save as.

I'll try to create a small project reproducing the issue.

**Comment by paulcwarren** [comment]
A project may not be necessary @estebes.

I have a theory.  When you click that 'download' I think your browser might *not* be sending an `Accept` header in the request.  In ContentEntityRestController (https://github.com/paulcwarren/spring-content/blob/949a73d5216b92f7e96c31e0f25bf571d47af698/spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/ContentEntityRestController.java#L122) we call a spring class to parse the mime-types received in the request's accept header.  If there aren't any it returns an immmutable list that we then try and add to.  This throws the UnsupportedOperationException.  

So I wonder what browser you are using and whether you could check the request it is sending.

Look forward to hearing from you.

**Comment by paulcwarren** [comment]
Yeah, I think that is what is going on.  I just managed to reproduce that error in a unit tests anyways.  Your context will be helpful but i am going to go ahead and fix this as it is a bug anyways.

**Comment by estebes** [comment]
So i just tried to use firefox instead of chrome and it actually works on firefox although you probably already know that by now but yes what you described seems to be what is happening.

**Comment by paulcwarren** [comment]
I added a candidate fix for this issue in this commit:-

https://github.com/paulcwarren/spring-content/commit/294fa48086ffcca21581dbc28de829eee88e182c

Can you switchover to 0.0.8-SNAPSHOT and give it a whirl.  If it fixes the issue then I'll cut a release.

**Comment by estebes** [comment]
Perfect fix. Works on both chrome and firefox. I think i can now close this issue. Thank you very much for the help.

**Comment by paulcwarren** [comment]
+1
