### ISSUE TITLE
Error on deleting the content on Windows

### ISSUE THREAD

**Issue by sandip-bhoi** [paulcwarren/spring-content#17]
The content does not get deleted from file system while unset the content on delete operation.
Creates exception "Unable to delete file: ".

OS: Windows 7.

**Comment by paulcwarren** [comment]
We were leaving an inputstream of the content unclosed in the REST later.  Fixed in https://github.com/paulcwarren/spring-content/commit/1d39e142f11f9413a7cc2cd2416a016ac3d90110.
