### ISSUE TITLE
Crash when use FileSystemResourceLoader in the latest version of spring boot

### ISSUE THREAD

**Issue by vincenting** [paulcwarren/spring-content#1701]
**Describe the bug**
When upgrading the spring framework, the system can't boot with an error outputted

```
The following method did not exist:

    'void org.springframework.util.Assert.notNull(java.lang.Object)'
```

In our latest branch, we are using `notNull(root)` 
https://github.com/paulcwarren/spring-content/blob/1a29e4f64642068217fa16b206cd4dc2a02dba5a/spring-content-fs/src/main/java/org/springframework/content/fs/io/FileSystemResourceLoader.java#L38

Which has been marked as Deprecated in the [previous version](https://docs.spring.io/spring-framework/docs/5.3.4/javadoc-api/org/springframework/util/Assert.html#notNull-java.lang.Object-). And now has been totally removed. 

**To Reproduce**
1. Upgrade Spring or Spring Boot to the latest version. `id 'org.springframework.boot' version '3.2.0'`
2. `new FileSystemResourceLoader(rootPath)`

**Expected behavior**
Use the `notNull(Object object, String message)` instead.

**Comment by paulcwarren** [comment]
Many thanks for the PR @vincenting.  I will cut a release on Friday
