### ISSUE TITLE
Not compatible with Spring Boot 3.2: method Assert.notNull(Object) does not exist

### ISSUE THREAD

**Issue by rschev** [paulcwarren/spring-content#1705]
**Describe the bug**
When running with Spring Boot 3.2, the application refuses to start. The FileSystemResourceLoader tries to call `void org.springframework.util.Assert.notNull(java.lang.Object)`, but [the documentation indicates that it needs a second argument](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/Assert.html#notNull(java.lang.Object,java.lang.String)).

**To Reproduce**
1. Download an empty Spring Boot 3.2 application from start.spring.io
2. Add `implementation 'com.github.paulcwarren:spring-content-fs-boot-starter:3.0.6'` to build.gradle
3. `./gradlew bootRun` and see the error.

**Comment by paulcwarren** [comment]
Thanks @rschev .  I believe that @vincenting just fixed this with #1702 .  I plan to cut a release this Friday

**Comment by paulcwarren** [comment]
I believe this is fixed in 3.0.6 and 3.0.7 but let me know if not.
