### ISSUE TITLE
Filesize and filename are not set after a multipart/form POST http request to create entity with content

### ISSUE THREAD

**Issue by NielsCW** [paulcwarren/spring-content#1818]
**Describe the bug**
User wants to create an entity with content by using a multipart/form POST http request.
The file in the request contains the entity content property name as name, an original filename, a content-type and the content in bytes.

**To Reproduce**
Add following `assertThat` statements to [this test](https://github.com/paulcwarren/spring-content/blob/3.0.8/spring-content-rest/src/test/java/it/internal/org/springframework/content/rest/controllers/ContentEntityRestEndpointsIT.java#L224):
```
Context("given a multipart/form POST to an entity with a single uncorrelated content property", () -> {
	It("should create a new entity and its content and respond with a 201 Created", () -> {
		...
		Optional<TestEntity3> fetchedEntity = repo3.findById(Long.valueOf(StringUtils.substringAfterLast(location, "/")));
		...
		assertThat(fetchedEntity.get().getLen(), is(file.getSize()));
		assertThat(fetchedEntity.get().getOriginalFileName(), is(file.getOriginalFilename()));
		...
	}
}
```

**Expected behavior**
Filename and filesize of the content are stored and match with the file the user sent.

**Additional context**
The MimeType of the content is correctly set after the multipart/form POST request.

**Comment by paulcwarren** [comment]
I did forget those two properties.  Many thanks @NielsCW
