### ISSUE TITLE
StoreRestResource deprecated or something?

### ISSUE THREAD

**Issue by oOBlinkOo** [paulcwarren/spring-content#184]
I'm new on Spring-content and I'm trying to implement it.
what should I use insted of StoreRestResource?

```
@StoreRestResource
public interface PictureContentStore extends ContentStore<User, String> {
}
```
These guides use StoreRestResource
https://paulcwarren.github.io/spring-content/spring-content-fs-docs/
https://paulcwarren.github.io/spring-content/spring-content-rest-docs/
https://paulcwarren.github.io/spring-content/refs/release/fs-index.html

spring-content-fs-boot-starter should contain that?
Regards
Any help would be appreciated!

**Comment by paulcwarren** [comment]
Hi @oOBlinkOo, 

`@StoreRestResource` is the annotation you use to export a Store through the Spring Content REST API.  Unless you need to customize the path, or link relation then technically it isn't necessary but either way, it isn't deprecated.  

What version of Spring Content are you using?  
What store and API modules are depending on?   spring-content-fs and spring-content-rest?  
What endpoint are you trying to use?  what is the request you are making (including headers).
are you getting a specific error?

Thanks

**Comment by paulcwarren** [comment]
Ping @oOBlinkOo.  any update on this?

**Comment by oOBlinkOo** [comment]
@paulcwarren It works, I wasn't adding spring-content-rest. Thanks for your help!
