### ISSUE TITLE
SQL Server

### ISSUE THREAD

**Issue by mrhcon** [paulcwarren/spring-content#1944]
Hi,
I am getting absolutely terrible performance with SQL Server using 2.9.0.  A 1.5 MB file took over 3 min to write from a stream to the database.  It's in the IOUtils.copyLarge() method at 4096 bytes at a time.
Does anyone have any recommendations?
Thanks.

**Comment by paulcwarren** [comment]
Thanks for the report.  Should be pretty easy to make the buffer size configurable if that would be helpful?  Are you using the content jpa starter?  i.e. can I add a buffer size property to that?
