### ISSUE TITLE
JPA Versioning repository not working correctly at new created Items

### ISSUE THREAD

**Issue by tim-boerner** [paulcwarren/spring-content#2039]
I started spring content JPA implementation with version 3.0.4 and updated now to 3.0.11. At both version a got unexpected behavior when using versioning repository implementations on new created items.

**findAllVersions(S var1)**
3.0.4: returns all new items, not only that one version of the new item
3.0.11: returns no objects

**deleteAllVersion(T var1)**
3.0.4: deletes all new items, not only that one version of the new item
3.0.11: does nothing, fails silently

The query of that methods are using "AncestralRootId = null". This was working at 3.0.4 with unexpected result and is not working at 3.0.11 because of the change at #1727 . I think a AncestralRootId value of null is just not expected here.

In my opinion there could be 2 solutions:
1. check if the item is new and if yes use methods without version (this is what i have done now in my code)
2. check if the item is new and if yes throw an exception (e.g. UnsupportedOperation)

**Additional context**
I am on Spring boot 3.2.4

**Comment by paulcwarren** [comment]
Hi @tim-boerner , that is interesting.  #1727 was addressing an issue at the time.  I dont recall exactly what it was actually but some of the findAllVersions tests were failing.  I had used `IS NULL` elsewhere and those tests where green.  Modifying this query to `IS NULL` seemed to make these ones go green too  

I have test cases for these so I wonder if it is an older version of Spring Boot pulling in older hibernate libraries or something like that.

**Comment by paulcwarren** [comment]
This [test](https://github.com/paulcwarren/spring-content/blob/14e611f99a10c4d95fa8b9ddce5d62dfdc537111/spring-versions-jpa/src/test/java/org/springframework/versions/impl/JpaLockingAndVersioningRepositoryImplIT.java#L419) should be the one testing the behavior you describe.  Currently [green](https://github.com/paulcwarren/spring-content/actions/runs/9885454862/job/27303507585) in CI.

I think you are saying that in SC 3.0.4 it would returns all versions of all entities?  And in 3.0.11 fails.  Can you check and make sure I am understanding.  Trying to see what I am missing here.

**Comment by tim-boerner** [comment]
On additional fact is, that i was using spring boot 3.1.1 when i was implementing SC 3.0.4. At Spring boot 3.1.1 hibernate queries which contains `= null` were working. At Spring boot 3.2.4 this needs to be chaned to `IS NULL`, as you have done it. The findAllVersions has not been changed and still uses `IS NULL`. When i changed that query to use IS NULL it returns to many result, basicly all entities, which are in new state and dont have set a AncestralRootId. So that would not be the solution.

About your test ...
```
BeforeEach(() -> {
          setupSecurityContext("some-principal", true);
          e1 = repo.save(e1);
          e1 = repo.lock(e1);
          e1v11 = repo.version(e1, new VersionInfo("1.1", "Minor"));
          e1v11 = repo.unlock(e1v11);
          e2 = repo.save(e2);
          e2 = repo.lock(e2);
          e2v2 = repo.version(e2, new VersionInfo("2.0", "Major"));
          e2v2 = repo.unlock(e2v2);
});

It("should return the version series", () -> {
         List<TestEntity> results = repo.findAllVersions(e1, Sort.by(Order.desc("id")));
         assertThat(results.size(), is(2));
         assertThat(results, Matchers.hasItems(hasProperty("xid", is(e1.getXid())), hasProperty("xid", is(e1v11.getXid()))));
});
```

As far as i can see, two version of entity e1 are created, then the entity is not new anymore and the code will work. What i mean is following:

```
BeforeEach(() -> {
         setupSecurityContext("some-principal", true);

         e1 = repo.save(e1);
});

It("should return the version series", () -> {
         List<TestEntity> results = repo.findAllVersions(e1, Sort.by(Order.desc("id")));
         assertThat(results.size(), is(1));
});
```

Running this at main branch returns 21 items instead of 1.

**Comment by paulcwarren** [comment]
I see.  If the entity has not yet been versioned then ancestor root id is null and query returns all such like entities.  But expectation is that it returns just that entity.

**Comment by paulcwarren** [comment]
Hi @tim-boerner , I've merged a potential fix tonight.  If you hve time and ability to do so can you give it a try and let me know.

I am in two minds about the behavior of deleteAllVersions when given an entity with no versions.  I made it delete the entity itself but I am wondering if that is the right default.  Or if it should be configurable to suit.

Also I was wondering if you are using the spring versions rest API, or not?

Thanks

**Comment by tim-boerner** [comment]
Looks good to me.
I am not using the versions rest API.
