### ISSUE TITLE
MySQLBlobResource SQL statement makes MySQL to always return "content" as content

### ISSUE THREAD

**Issue by dkaspar** [paulcwarren/spring-content#207]
I am using Spring (2.2.x) and spring-content-jpa (1.0.0:M10) and mysql-connector-java (5.1.48) in my application with DataSource to my MySQL server.

It seems that ContentStore.getContent() method always returns InputStream and reading it ways returns string "content" (aka 7 bytes).

I have checked the database and it has the blob correctly stored there. It seems to be related to:
internal.org.springframework.content.jpa.io.MySQLBlobResource.getSelectBlobSQL() method which is implemented as:

    return "SELECT id, 'content' as content FROM BLOBS WHERE id='" + id + "'";

while it should be:

   return "SELECT id, content FROM BLOBS WHERE id='" + id + "'";

Could this be fixed? Or is there any issue my application?

**Comment by dkaspar** [comment]
It seems that this might be related to MySQL Server which might require to have SQL_MODE=ANSI_QUOTES

**Comment by paulcwarren** [comment]
@dkaspar thanks for giving spring-content a try.

As described in the [reference guide](https://paulcwarren.github.io/spring-content/refs/snapshot/1.0.x/jpa-index.html#_annotation_based_configuration)?  See section 2.1.1 you need to enable locator emulation by specifying the attribute `emulateLocators=true` on your jdbc connection string. 

In case it is use this has been discussed in a [previous issue](https://github.com/paulcwarren/spring-content/issues/60) too.

**Comment by dkaspar** [comment]
Thanks for the pointing me to the documentation - I have completely overlooked it and did not realized that might be connected.

Thank you very much for the answer. Closing the issue.
