### ISSUE TITLE
spring-content jar missing from the maven repository

### ISSUE THREAD

**Issue by repantoja** [paulcwarren/spring-content#2094]
**Describe the bug**
Hi Paul,
I was trying to use the new version of spring content but when I do install dependencies the spring-content jar is missing from the maven repository I check to make sure and the only thing that I see is the poem not the .jar file.
am I missing something.
thanks for your help

**To Reproduce**
install spring-content maven project

**Expected behavior**
Can't find dependency on maven repository

**Comment by paulcwarren** [comment]
Well I am not sure.  That is curious.  I can see them [there now](https://mvnrepository.com/artifact/com.github.paulcwarren/spring-content-commons/3.0.14) though so maybe you just got unlucky and tried to bump your Spring Content right after I made the release perhaps?  It does take a few hours for the JARs to appear on maven central.

**Comment by repantoja** [comment]
Paul thanks for your response. I was referring to following dependency.
https://mvnrepository.com/artifact/com.github.paulcwarren/spring-content/3.0.14
so is the spring-content the same as spring-content-common?
because the pom file for spring-content-common is looking also for the spring-content but it can't find the jar
thanks for your help

**Comment by paulcwarren** [comment]
The spring-content module is of [type pom](https://github.com/paulcwarren/spring-content/blob/main/pom.xml#L7).  It collects all of the spring content modules together into a single build.  Therefore, when published, is a pom only and does not have a jar.  

Can you explain what you are trying to do?  Are you trying to build Spring Content yourself?  Or are you declaring a dpeendency from your project?  If so which one?

**Comment by repantoja** [comment]
I was adding spring-content on my dependencies since I am upgrading from an old version. I didn't notice that I didn't have to.
so I just fixed it.
Thanks for your help and quick response.

**Comment by paulcwarren** [comment]
Glad you got it fixed.
