### ISSUE TITLE
searchContent/findKeyword Cause java.lang.IllegalArgumentException: wrong number of arguments

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#222]
ContentSearchRestController' searchContent/findKeyword invoke to Searchable.findKeyword ,but findKeyword does't have a Pageable param ,

http://localhost:8080/archives/api/v1/documents/searchContent/findKeyword?keyword=RocketMQ

version: 1.0.0.M10

**Comment by paulcwarren** [comment]
The currently supported endpoint for fulltext search is `searchContent` @lmtoo; i.e. something like `curl -H 'Accept:application/hal+json' http://localhost:8080/files/searchContent?queryString=Content` is a valid search query.

You can read a little bit more in the [getting started guide](https://paulcwarren.github.io/spring-content/spring-content-with-fulltext-docs/).

We should clean the other endpoint up I think.

**Comment by lmtoo** [comment]
The document [search](https://paulcwarren.github.io/spring-content/refs/release/1.0.0.M10/rest-index.html#_search) and [search content resource](https://paulcwarren.github.io/spring-content/refs/release/1.0.0.M10/rest-index.html#_the_searchcontent_resource ) is inconsistent

**Comment by paulcwarren** [comment]
Documentation fixed with https://github.com/paulcwarren/spring-content/commit/915b9cafe67e3b49d260aba3f7b48ae6ed6eafa4

**Comment by paulcwarren** [comment]
In the end was this just the documentation issue @lmtoo?  Or are you still seeing the illegalArgumentException?  And if so can you post the request you are making please?

**Comment by lmtoo** [comment]
/searchContent/findKeyword?keyword=RocketMQ will case this exception , but if only /searchContent?queryString=RocketMQ is allowed ,  this is well , I well ignore this endpoint

**Comment by paulcwarren** [comment]
OK.  Yes the findKeyword method of access is deprecated but we actually do still [test this](https://github.com/paulcwarren/spring-content/blob/43c9e2b3c93b4a0a5f6377344eb51b652874be60/spring-content-rest/src/test/java/internal/org/springframework/content/rest/controllers/ContentSearchRestControllerIT.java#L408) and it is green in CI.   

I wonder are you putting an `accept: application/hal+json` header on the request?

**Comment by paulcwarren** [comment]
Closing.  Please feel free to reopen if we need to work on this further.
