### ISSUE TITLE
auto config docx4j'RenditionProvider when spring-content-docx4j on classpath

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#226]
when I introduce spring-content-docx4j, WordToHtmlRenditionProvider/WordToTextRenditionProvider is not being auto configed , JpegToPngRenditionProvider and WordToPdfRenditionProvider is not annotated with @Component or @Service

**Comment by paulcwarren** [comment]
This make sense.  We can do this.

**Comment by paulcwarren** [comment]
- [X] Annotate all renderers as `@Service`s 
- [X] Add a `Docx4jConfiguration` class that should be imported to extend the component scan to find/add the docx4j renderers to the rendition service
- [ ] Add componentscan to the renditions spring boot starter
