### ISSUE TITLE
BeforeSetContentEvent can't get MimeType and OriginalFileName from entity

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#227]
@HandleBeforeSetContent's only argument BeforeSetContentEvent can't get MimeType and OriginalFileName from event.source

**Comment by paulcwarren** [comment]
@lmtoo 

It is possible to configure an event handler like this:

```
@StoreEventHandler
public class ExampleAnnotatedEventListener {

	@HandleBeforeGetContent
	public void onBeforeGetContent(Product product) {
		...type-safe handling logic for Product's and their content before it is fetched
	}
}
```

i.e. to accept the event source object as a strongly typed argument so that you can use its getters to fetch the relevant attributes.  In this case you could call getMimeType() and getOriginalFileName().

Would this work for you?

**Comment by lmtoo** [comment]
before set content，I' would calculate pages by mimeType or filename's suffix, like this:

`@HandleBeforeSetContent
    fun beforeSetContent(event: BeforeSetContentEvent) {
        val document = event.source as? Document ?: return
        when(document.mimeType'){
          'pdf'-> { 
            val reader = PdfReader(event.`is`)
            document.totalPages = reader.numberOfPages
          },
          'docx'-> {
            calculate doc's pages by another tool
          }
       }
    }`

**Comment by paulcwarren** [comment]
Not a kotlin user so...yes i think this is an option.  I assume you could also do this too:

```
 @HandleBeforeSetContent
    fun beforeSetContent(document: Document) {
        when(document.mimeType'){
          'pdf'-> { 
            val reader = PdfReader(event.`is`)
            document.totalPages = reader.numberOfPages
          },
          'docx'-> {
            calculate doc's pages by another tool
          }
       }
    }
```

Which might be marginally more efficient?  But, like I say, haven't done any kotlin so guessing really.  But, from a Spring Content perspective this is possible.

**Comment by lmtoo** [comment]
but I can't get inputStream from entity in this way

**Comment by lmtoo** [comment]
If I use BeforeSetContentEvent，I can't calculate pages by mimeType or filename's suffix, because 
 when the event method is called, entity's properties is not populated  :

 @HandleBeforeSetContent
    fun beforeSetContent(event: BeforeSetContentEvent) {
        val document = event.source as? Document ?: return

         ##document.mimeType is null here, and originalFileName also is null

        when(document.mimeType){
          'pdf'-> { 
            val reader = PdfReader(event.`is`)
            document.totalPages = reader.numberOfPages
          },
          'docx'-> {
            calculate doc's pages by another tool
          }
       }
    }

**Comment by lmtoo** [comment]
> before set content，I' would calculate pages by mimeType or filename's suffix, like this:
> 
> ```
>  @HandleBeforeSetContent
>     fun beforeSetContent(event: BeforeSetContentEvent) {
>         val document = event.source as? Document ?: return
>         when(document.mimeType'){
>           'pdf'-> { 
>             val reader = PdfReader(event.`is`)
>             document.totalPages = reader.numberOfPages
>           },
>           'docx'-> {
>             calculate doc's pages by another tool
>           }
>        }
>     }
> ```

I can't get inputStream from entity in this way

**Comment by lmtoo** [comment]
> @lmtoo
> 
> It is possible to configure an event handler like this:
> 
> ```
> @StoreEventHandler
> public class ExampleAnnotatedEventListener {
> 
> 	@HandleBeforeGetContent
> 	public void onBeforeGetContent(Product product) {
> 		...type-safe handling logic for Product's and their content before it is fetched
> 	}
> }
> ```
> 
> i.e. to accept the event source object as a strongly typed argument so that you can use its getters to fetch the relevant attributes. In this case you could call getMimeType() and getOriginalFileName().
> 
> Would this work for you?

I can't get InputStream in this way

**Comment by paulcwarren** [comment]
I think I have confused things by using `HandleBeforeGetContent` instead of `HandleBeforeSetContent`.  Sorry about that.

**Re InputStream access**
So, on your inputstream point.  StoreEventHandlers are just regular old beans so you can autowire your store into your event handler in order to perform content operations, something like this in Kotlin perhaps? 

```
class MyStoreEventHandler {

@Autowired
MyStore store;

@HandleBeforeSetContent
    fun beforeGetContent(document: Document) {
      ...store.getContent(document)...
    }
```

**HandleBeforeSetContent Entity Property Access**
But on the properties not yet being set in the before set content event handler (which I am now thinking is your real issue) then yeah, in general, these are set *after* the content operation.  

So I wonder if you could use HandleAfterSetContent instead of HandlerBeforeSetContent?  Properties should be set and content available to you.  You could autowire the document repository and document store into your (strongly types) event handler in order to calculate the number of pages from the content stream, then update the entity, then save it?

**Comment by lmtoo** [comment]
yes , use HandleAfterSetContent and then update document by DocumentRepository may could do this. I will try this later

**Comment by paulcwarren** [comment]
Thanks.  Please let me know.

**Comment by lmtoo** [comment]
gave up multi mimeType support now , only use PDF

**Comment by paulcwarren** [comment]
Had a bit of time to sit down and look at this tonight.  I realized that neither before set of after set event handler would work with the current implementation.  

I think it is fine to set the attributes you are after before setting the content so they are available in either event handler.

**Comment by paulcwarren** [comment]
Fixed with https://github.com/paulcwarren/spring-content/commit/770114cd7209b9a6be0a87dcf4b605cf38dd7019
