### ISSUE TITLE
internal.org.springframework.content.elasticsearch.boot.autoconfigure.ElasticsearchAutoConfiguration should annotated with @AutoConfigureAfter(org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientAutoConfiguration.class)

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#230]
when I intruduce org.elasticsearch.client:elasticsearch-rest-high-level-client ,org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientConfigurations.RestHighLevelClientConfiguration will auto config with spring.elasticsearch.rest.uris=http://192.168.2.215:9200, but internal.org.springframework.content.elasticsearch.boot.autoconfigure.ElasticsearchAutoConfiguration#restHighLevelClient happens before that configuration , and a localhost elasticsearch service is required

**Comment by paulcwarren** [comment]
Hmmm...this seems difficult to achieve.  I understand why you want to do this and it makes sense.  I think we should do it.  But the spring boot classes are package private and even using the @AutoConfigureAfter(name= doesn't appear to work with package private classes.

**Comment by paulcwarren** [comment]
Fixed with https://github.com/paulcwarren/spring-content/commit/997151e5762c18af5065989a1325d59a06038b48
