### ISSUE TITLE
I can't disable spring-content-elasticsearch when I only needs spring-data-elasticsearch

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#235]
please provide @ConditionalOnProperty(prefix = "spring.content.elasticsearch", name = ["enabled"], havingValue = "true", matchIfMissing = false) on internal.org.springframework.content.elasticsearch.boot.autoconfigure.ElasticsearchAutoConfiguration, 
When I plan to implementation FullText by myself , I found ElasticsearchAutoConfiguration well auto config when spring-content-elasticsearch is not on classpath, and this will case java.io.FileNotFoundException: class path resource [internal/org/springframework/content/elasticsearch/ElasticsearchConfig.class] cannot be opened because it does not exist

**Comment by paulcwarren** [comment]
Fixed with https://github.com/paulcwarren/spring-content/commit/0ff18784372fc0f883f8b97bdc37af1d347416de
