### ISSUE TITLE
Problem with multi-module project.

### ISSUE THREAD

**Issue by wattfarnas97** [paulcwarren/spring-content#278]
hi,I have to create spring boot multi-module project. When I do autowired to my  content store interface, I  obtain this  error.

```
Field photoStore in com.orienkadi.api.service.compass.CompassServiceImpl required a bean of type 'com.orienkadi.domain.repository.ProfilPicture' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:
Consider defining a bean of type 'com.orienkadi.domain.repository.ProfilPicture' in your configuration.
```
I don't understand because i can use my  jpa repositories.

```
	 @Service
@Transactional
public class CompassServiceImpl  implements ICompassService{
		  @Autowired private ProfilPicture photoStore;
}
```

```
public interface ProfilPicture  extends ContentStore<User, Long>{

}
```

```
@SpringBootApplication
@ComponentScan(basePackages = {"com.orienkadi.*"})
@EntityScan(basePackages = {"com.orienkadi.*"})
@EnableJpaRepositories(basePackages = {"com.orienkadi.*"})
@EnableAutoConfiguration

public class OrienkadiApplication implements CommandLineRunner {

	  public static void main(String[] args) {

	        SpringApplication.run(OrienkadiApplication.class);
	    }
	  @Bean
		public BCryptPasswordEncoder  getBCE(){
			return new BCryptPasswordEncoder();
		}
	    @Bean
	    public RequestContextListener requestContextListener() {
	        return new RequestContextListener();
	    }
	
	@Override
	public void run(String... args) throws Exception {
	
	}
}       

```

**Comment by paulcwarren** [comment]
This sounds curious.  

Just to clarify is this a problem in the IDE only?  Or does the application actually fail to start?

If the application is failing to start then can you supply the full stack trace pls?

**Comment by wattfarnas97** [comment]
finally  add   `@EnableFilesystemContentRepositories(basePackages  = {"com.orienkadi.*"} )` to my main function seem  to resolve my  problem.


```
@EnableAutoConfiguration
@SpringBootApplication(scanBasePackages  = "com.orienkadi")
@ComponentScan(basePackages = {"com.orienkadi.*"})
@EntityScan(basePackages = {"com.orienkadi.*"}) @EnableJpaRepositories(basePackages = {"com.orienkadi.*"})
@EnableFilesystemContentRepositories(basePackages  = {"com.orienkadi.*"} )
@EnableTransactionManagement
public class OrienkadiApplication implements CommandLineRunner {

	  public static void main(String[] args) {

	        SpringApplication.run(OrienkadiApplication.class);
	    }
	  @Bean
		public BCryptPasswordEncoder  getBCE(){
			return new BCryptPasswordEncoder();
		}
	    @Bean
	    public RequestContextListener requestContextListener() {
	        return new RequestContextListener();
	    }
	    
	 
	@Override
	public void run(String... args) throws Exception {
	
	}
} 
```

**Comment by paulcwarren** [comment]
I did see that you were missing an `@EnableXXXStores` annotation but assumed you were relying on autoconfiguration to enable it.

`@EnableFilesystemContentRepositories` will work but know it is deprecated in favor of `@EnableFilesystemStores` and we may remove it at some point in the future.

Glad you got it working.

**Comment by wattfarnas97** [comment]
thanks for the assist

**Comment by forSale** [comment]
Hello
I have the same issue in spring boot project version 2.7.8.
I have module with main start up class and another module where ContentStore extending interface is located. When start app it fails with this
***************************
APPLICATION FAILED TO START
***************************
Parameter 3 of constructor in MyImpl required a bean of type 'FileContentStore' that could not be found.


Action:

Consider defining a bean of type 'FileContentStore' in your configuration.

FileContentStore extends ContentStore

**Comment by forSale** [comment]
But in single module app everything works fine.
