### ISSUE TITLE
Image file always auto download when src is setting to content link

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#310]
Image file always auto download when 

`<img src='http://localhost:8085/inspection/api/v1/content/146'/>`

 src is setting to content link , a way to disable auto download or provide a Content-Disposition configuration

**Comment by paulcwarren** [comment]
Hi @lmtoo, can I clarify?  Do you mean that the image is downloading to the client, or just being displayed on the web page?

**Comment by lmtoo** [comment]
It”s display by the src attribute ，but It”s download at the same time，I want to control this behavior by mimeType

**Comment by paulcwarren** [comment]
I see.  I am not seeing that behavior.  Always just displayed but not downloaded.

Currently using:
Chrome 84.0.4147.105 
Firefox 74.0
Safari 13.0.5 

I wonder what you are using?  Although this doesn't feel like a browser issue.

**Comment by lmtoo** [comment]
So sorry, my mistake
