### ISSUE TITLE
NoSuchMethodError with MongoDB and Spring Boot 2.0.6

### ISSUE THREAD

**Issue by ramymagdy** [paulcwarren/spring-content#32]
Spring boot uses spring-data-mongodb v2.0.6 and the signature of the store function in org.springframework.data.mongodb.gridfs.GridFsTemplate class have changed from:

public GridFSFile store(InputStream content, String filename)

to:

 public ObjectId store(InputStream content, String filename)

java.lang.NoSuchMethodError: org.springframework.data.mongodb.gridfs.GridFsTemplate.store(Ljava/io/InputStream;Ljava/lang/String;)Lcom/mongodb/gridfs/GridFSFile;
	at internal.org.springframework.content.mongo.repository.DefaultMongoStoreImpl.setContent(DefaultMongoStoreImpl.java:54)

**Comment by paulcwarren** [comment]
Hey @ramymagdy the current code line 0.0.x is based on Spring Boot 1.5.x.  We are planning to cut a release 0.0.11 this week and then master will be rebased onto Spring Boot 2 (currently sitting on a wip/springboot2 branch).  This will be release as 0.x (leaving 0.0.x as Boot 1 in case we need to bug fix).  We'll address this issue then.  Timeline wise we are probably looking at the week after next for that.

**Comment by paulcwarren** [comment]
Hey @ramymagdy.  We just cut release `0.1.0` that updates our Spring Boot dependency to `2.0.2` which pulls in Spring Data Mongo `2.0.7`.  I think that you should be good now.  Will close this but feel free to re-open if you find any have issues.
