### ISSUE TITLE
basePackageClasses for packages in external libraries

### ISSUE THREAD

**Issue by pulse00** [paulcwarren/spring-content#33]
We use an internal library which enables a `FilesystemStore` using the following config class:

```java
  @Configuration
  @EnableFilesystemStores(basePackageClasses = {ContentStores.class})
  public static class FileStoreConfig {

  }
```

This configuration is included from within the spring boot context in our applications. The creation of the ContentStores defined in the `ContentStores` package are working fine when starting from within the IDE, but fail when deployed on the server.

Does the `basePackageClasses` support using classes in external libraries?

**Comment by paulcwarren** [comment]
Hi pulse000,
Thanks for using Spring Content.  
If I understand it your Spring Content stores are arranged into different modules (jars) from the loading spring application context.   To double check this I created a sample project [here](https://github.com/paulcwarren/spring-content-issue-33) that demonstrates how this works - or should work.
Can you confirm whether this is equivalent to your setup, or not?  And we can take it from there.
_Paul

**Comment by pulse00** [comment]
Hi @paulcwarren 

thanks for this project and taking the time for the sample project. I've forked it to demonstrate how we've structured our projects - however the sample project does not fail with the updated setup.

https://github.com/pulse00/spring-content-issue-33/tree/issue-33

I'll get back to you as soon as we've figured out what was the issue.

**Comment by paulcwarren** [comment]
I see.  Yeah, I think the two setup amount to the same.  Let me know what you find out.  Let me know if I can be of assistance.  We'll leave this open for a bit in case there is anything you want to ask/discuss.

**Comment by pulse00** [comment]
@paulcwarren sorry about the fuzz, it's working now - i think there where some weird dependency issues in our project - i brought all spring-data (content) related dependencies to the same version and everything is working now as expected. 

One more thing: Are you fine with using github issues for questions regarding the library usage or do you prefer another channel?
