### ISSUE TITLE
package com.emc.spring.content.commons.annotations does not exist

### ISSUE THREAD

**Issue by davidktw** [paulcwarren/spring-content#34]
Hi Paul,

It's great to see Spring Content for Headless CMS. I was trying out and while compiling, I encounter missing packages for the annotation used. May I enquire how should this be resolve ? Thanks for the effort.

**Comment by paulcwarren** [comment]
Thanks for giving Spring Content a try.  This seems a little odd.  That package does not exist in the current code-line.  Where exactly have you grabbed the code from?  Are you planning to change the code?  Is that why you grabbed the code?  We publish the JARs to maven so you can grab them using maven or gradle.

**Comment by davidktw** [comment]
Hi Paul,

I found those lines of code in your startup guide found at https://paulcwarren.github.io/spring-content/spring-content-fs-docs/
under the “Define a simple Entity” section.
Is this guide outdated, and where should I be looking?

Thanks
David

**Comment by paulcwarren** [comment]
No you are right.  The guide was outdated.  We kept the repo's up-to-date but let the guides themselves lapse.  I have fixed them up for you.  Time to upgrade to asciidoc so tat we can just import the source files into the guides I guess.  Sorry about that.

**Comment by davidktw** [comment]
I see, thanks for the highlight and update. :)

**Comment by paulcwarren** [comment]
OK.  I'll leave this open for a few days in case you have anymore issues.  Please let me know.

**Comment by paulcwarren** [comment]
I assume this is now resolved.  Closing.  Just shout if you have any more issues.
