### ISSUE TITLE
@RestResource(exported=false) ignored on unsetContent (and others?)

### ISSUE THREAD

**Issue by michelkaeser** [paulcwarren/spring-content#355]
Hello!

Given the following store interface:

```
@StoreRestResource(path="files", linkRel="file")
public interface FileContentStore extends ContentStore<File, UUID> {

    @Override
    @RestResource(exported=false)
    File setContent(File file, InputStream content);

    @Override
    @RestResource(exported=false)
    File setContent(File file, Resource resourceContent);

    @Override
    @RestResource(exported=false)
    File unsetContent(File file);

    @Override
    @RestResource(exported=false)
    void associate(File file, UUID id);

    @Override
    @RestResource(exported=false)
    void unassociate(File file);

}
```

I would expect all requests to the store controller except retrieval to return `405 Method Not Allowed` but actually deleting the content still works. The `@RestResource(exported=false)` annotation does not seem to be honored.

**Comment by paulcwarren** [comment]
When I added the `Resource(export=false)` annotation I only added it to `setContent` as it was part of another story to support a new API method `setContent(S entity, Resource r)` on ContentStore.  I wanted to get that done for the requester so I punted on adding support for it to the other methods.

I have added unsetContent tonight ([commit](https://github.com/paulcwarren/spring-content/commit/e1097966f7eee7c1de01d9f803640f25abeb3d55)).  I had to do a little refactoring to tidy up the implementation of `StoreRestController.getResource` so I didn't quite get to `getContent` but I will tomorrow and cut a release for you.

**Comment by paulcwarren** [comment]
Will be in next release 1.1.0.M4

**Comment by michelkaeser** [comment]
Thank you very much Paul! Any chance this can get backported to the Spring Boot 2.2.x branch as well?
Also generally asking, how is your policy for the different branches?

**Comment by paulcwarren** [comment]
Yes, I can try and backport but it might be tricky given the number of files and type of change.

Re branches.  In general I have been creating a new branch for each version of Spring Boot.  But I am going to move to a model where we only create a branch, if required (i.e. we are not able to bump successfully).  I haven't done the test for Spring Boot  2.4 yet but I think it will just be bumpable.

0.x branch (Spring Boot 1.5.x) is bug fixes only now, considering deprecating it as it looks like Spring Boot 1.x is out of support.

1.0.x (Spring Boot 2.2.x) is technically bug fixes only but I will make a best effort to backport features if requested.

1.1.x (Spring Boot 2.3.x) is the active dev/release branch currently.

Is something stopping you from bumping to Spring Boot 2.3?  Or is it something in Spring Content 1.0.x/1.1.x transition?

**Comment by michelkaeser** [comment]
Hi Paul, sorry for getting back so late I was in vacation. Appreciating your branching/release explanation.

Actually Spring Boot 2.3.x caused some issues (validation beans/classes API changes) for us which kept us back upgrading at that time but it might be worth giving it another shot since that is very likely effort that can now be justified with this feature added here. 👍 

Again, thanks for this addition and your time to discuss. Looking forward to see this feature working in our hopefully soon 2.3.x code.
