### ISSUE TITLE
close resources

### ISSUE THREAD

**Issue by bilak** [paulcwarren/spring-content#4]
in [this](https://github.com/paulcwarren/spring-content/blob/master/spring-content-jpa/src/main/java/internal/org/springframework/content/jpa/operations/JpaContentTemplate.java) class no resource is ever closed (connection, resultset, statement). Which java version is this project targeted to (8?)?

**Comment by paulcwarren** [comment]
Whoops.  That is an oversight...We are targetting Java 8.

**Comment by paulcwarren** [comment]
Please see [this commit](https://github.com/paulcwarren/spring-content/commit/791c521c139c2fffa97fa7887310fedb49146ed5) and [this commit](https://github.com/paulcwarren/spring-content/commit/0f9b5ad4c93cce83342e68b2aa4fe94162195f39).

**Comment by bilak** [comment]
@paulcwarren it's still big mess. when are the connections closed? As example look at this:

`rs = datasource.getConnection().getMetaData().getTables(null, null, "BLOBS", new String[] {"TABLE"});` 

It could be rewritten to something like this:
```
try (Connection connection = datasource.getConnection()){
   try (ResultSet rs = connection.getMetaData().getTables(null, null, "BLOBLS", new String[]{"TABLE"})){
      ... do something other and connection and resultset will be released by try/catch autocloseable block.
   }
}
```

that also applies to  `Statement` class

**Comment by jeffpak** [comment]
@bilak Please see [this commit](https://github.com/paulcwarren/spring-content/commit/45a8576d1f5a9d9edf637ac6508522de3fb99c96). We didn't implement the fix exactly as you suggested, but decided instead to use the jdbc template. Does this satisfy your concerns?

Best,
Jeff & Paul

**Comment by paulcwarren** [comment]
Haven't heard back on this so I assume the later commit resolved the issues.
