### ISSUE TITLE
full customization of file content path

### ISSUE THREAD

**Issue by antocap** [paulcwarren/spring-content#40]
Dear Paul,

I am trying to use your Spring Content Filesystem api for a CMS project.

I would like to put each content in different folders depending on the corresponding site.
But the FilesystemStoreConverter receive only the Content Id and not the Entity that describes its metadata.

Of course I could query the Metadata Repository injecting it in the class in which I define the custom converter but I think that it would be better to pass to the convert method also the entity which holds the metadata, in order to give to the developer the means to create meaningful folders and filenames.

What do you think about this proposal?

Thank you very much for your work.

Best regards,
Antonio Capani

**Comment by paulcwarren** [comment]
Hi Antonio,

Firstly, thanks for giving Spring Content a try.  I hope it works out for you on this project. 

I believe I understand your proposal.  In fact, we did something similar for the s3 store recently.  To double check I do, in fact, understand what you are proposing I made this [wip commit](https://github.com/paulcwarren/spring-content/tree/wip-issue-40).  Don't expect the code to actually work it is just for us to discuss/agree.  

First impressions are good.  The approach is simple yet powerful.  I will think on it some more and see if I can find any gaps/issues.  In the meantime, let me know if this is what you were describing.

_Paul

**Comment by antocap** [comment]
Hi Paul,

thank you for your immediate answer.
I think you made exactly what I was asking for.

Best regards,
Antonio

**Comment by paulcwarren** [comment]
Great.  I will add tests.  Will be in the next release (0.2.0).

**Comment by antocap** [comment]
Thank you!

**Comment by paulcwarren** [comment]
Fixed by 5e0cb31a99b08cd53890e1de55fc9a8804544fae.

Let me know if you see any issues with this.
