### ISSUE TITLE
suggestion: remove empty dir on contentRepository.unsetContent

### ISSUE THREAD

**Issue by antocap** [paulcwarren/spring-content#41]
Hi Paul,

I have noticed that when I call unsetContent the dirs are not removed.
In general I think that the sequence...

// file system status = A
myContentRepository.setContent(myEntity, inputStream);
myContentRepository.unsetContent(myEntity);
// file system status = B

... should keep the file system unchanged (A = B).

Regards,
Antonio

**Comment by paulcwarren** [comment]
Sure.  I think we should be able to add logic to remove the folder path if it is empty.
