### ISSUE TITLE
RenderedResource try to convert , even acceptedMimeType is */*;q=0.8

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#412]
I have defined a Pdf2TextRenditionProvider ,which implements RenditionProvider , which consume application/pdf  and produce text/plain, but when I use pdf-js to preview pdf , pdf-js send a Accept: */* request, to access pdf content, which lead to invoke Pdf2TextRenditionProvider'convert method, and response with a 0 length file.

RenditionService shuold not convert when toMimeType is a not a specific mimeType

**Comment by paulcwarren** [comment]
Hi @lmtoo, just to confirm pdf-js sends a request with a header `Accept: */*`; i.e. it will accept anything?

**Comment by lmtoo** [comment]
yes, `Accept: */* ` means client can process anything ,  if we response original mimeType ,it can process too
