### ISSUE TITLE
Suggestion: DefaultFilesystemStoreImpl.setContent() should throw Exceptions in case of failure

### ISSUE THREAD

**Issue by antocap** [paulcwarren/spring-content#42]
For example, if the target directory for the content is not writeable, a IOError is thrown in the body of the setContent() method, but it is recovered with the code

`logger.error(String.format("Unexpected error setting content for resource %s",property.toString()), e);
`

I think that it would be better to throw an exception (something like CannotSetContent...) or, at least, the method should return a boolean with the status of the operation (eg: true for success and false for fail).

Thank you and best regards,
Antonio

**Comment by paulcwarren** [comment]
This makes sense.  Will make the store methods (most likely not just setContent) return StoreAccessExceptions (the equivalent of Spring Data's DataAccessException) when failures occur.
