### ISSUE TITLE
The response has a duplicate "Content-Length" header when get by range header

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#449]
## request

> GET /inspection/api/v1/binary/1568 HTTP/1.1
> Host: inspection.lubansoft.net:58888
> Connection: keep-alive
> Pragma: no-cache
> Cache-Control: no-cache
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
> Accept: */*
> Accept-Encoding: identity
> Accept-Language: zh-CN,zh;q=0.9
> Range: bytes=0-65535

## response

> HTTP/1.1 206 Partial Content
> Expires: 0
> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> X-XSS-Protection: 1; mode=block
> Pragma: no-cache
> Content-Disposition: form-data; name="attachment"; filename*=UTF-8''%E8%AF%84%E5%AE%9A%E8%A1%A810.3.2%20%E6%98%8E%E6%B4%9E%E6%B5%87%E7%AD%91%E5%88%86%E9%A1%B9%E5%B7%A5%E7%A8%8B%E8%B4%A8%E9%87%8F%E6%A3%80%E9%AA%8C%E8%AF%84%E5%AE%9A%E8%A1%A8%28SG%29.pdf
> Accept-Ranges: bytes
> Date: Mon, 21 Dec 2020 13:02:45 GMT
> Connection: keep-alive
> Content-Language: zh-CN
> X-Frame-Options: SAMEORIGIN
> ETag: "10"
> Vary: Origin
> Vary: Access-Control-Request-Method
> Vary: Access-Control-Request-Headers
> Last-Modified: Mon, 21 Dec 2020 06:02:31 GMT
> Content-Range: bytes 196608-212611/212612
> X-Content-Type-Options: nosniff
> Content-Length: 212612
> Content-Length: 16004
> Content-Type: application/pdf

in response header, Content-Length has two values , and chrome will have net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH error

**Comment by paulcwarren** [comment]
Hey @lmtoo,

I am having trouble reproducing this.  I think I set something up that approximates your setup.  Spring Content backend.  Mongo Storage.  pdf.js front end.  When pdf.js request a larger pdf and the server responds with `Accept-Ranges: bytes` then pdf.js makes a second request for a content range (as in your example I think).  Here are my request and responses:

## Request
```
GET /files/1 HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:8080/testpdf.html
Accept-Encoding: identity
Accept-Language: en-US,en;q=0.9
Range: bytes=1835008-1893493
```

## Response
```
HTTP/1.1 206
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Last-Modified: Wed, 30 Dec 2020 06:01:54 GMT
ETag: "1"
Accept-Ranges: bytes
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/octet-stream
Date: Wed, 30 Dec 2020 06:01:59 GMT
Keep-Alive: timeout=60
Connection: keep-alive
Content-Range: bytes 1835008-1893493/1893494
Content-Length: 58486
```

With my setup I only see a single Content-Length header in the response and pdf.js renders the document as expected.  I'll commit this project so we can collaborate on it.

**Comment by paulcwarren** [comment]
https://github.com/paulcwarren/issue-449.

Needs mongo running on default port on localhost.

**Comment by lmtoo** [comment]
I create a pull request https://github.com/paulcwarren/issue-449/pull/1 , It's seems about undertow

**Comment by paulcwarren** [comment]
Thanks.  Yeah, your theory is right I think.  It looks like it is a difference in how the underlying response class handles the content-length header.  

Firstly, `org.springframework.web.servlet.resource.ResourceHttpRequestHandler` (that we use to write content and partial-content responses) actually writes the content-length twice.  Once, with the entire content-length and then later on, if a partial-content response, with the range length.  

Tomcat handles this just fine accepting the last content-length set as the authoritative content-length and writes it back to the client.

Undertow seems to assume all headers are multi-value and writes both content-length headers back to the client.

So, I can see this as a bug in undertow AND a bug in `org.springframework.web.servlet.resource.ResourceHttpRequestHandler` as it is a bit lazy in how it writes headers.  And may try and massage this issue a little but and raise an issue against Spring webmvc in the first instance.

**Comment by lmtoo** [comment]
ok, thanks , I will report this to spring-mvc.
Another question, How can I config "Cache-Control" header for spring-content, It's alway return "Cache-Control: no-cache, no-store, max-age=0, must-revalidate" , even I have config spring.resources.cache.cachecontrol.max-age=300s

**Comment by paulcwarren** [comment]
Hi @lmtoo, can we remove this text from the spring bug you created (or replace it with what I know have above):

"So, I can see this as a bug in undertow AND a bug in org.springframework.web.servlet.resource.ResourceHttpRequestHandler as it is a bit lazy in how it writes headers. And may try and massage this issue a little but and raise an issue against Spring webmvc in the first instance."

Now, I have looked into it more it is not correct.  Thanks.

Will look into the Cache-Control.
