### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by jcantonio** [paulcwarren/spring-content#456]
Hello,

I am evaluating spring-content which looks promising. 
There is an issue with the documentation in the page:
https://paulcwarren.github.io/spring-content/
as starting from version 1.2, all reference documentations point to s3-index.html instead of the related documentation.

for example with elasticsearch:

```
<td>Spring Content Elasticsearch</td>
--
  | <td><a href="refs/release/0.12.0/elasticsearch-index.html">0.12.0</a></td>
  | <td><a href="refs/release/1.0.0.M10/elasticsearch-index.html">1.0.0.M10</a></td>
  | <td><a href="refs/snapshot/1.0.x/elasticsearch-index.html">1.0.0.M11</a></td>
  | <td><a href="refs/release/1.1.0.M5/elasticsearch-index.html">1.1.0.M5</a></td>
  | <td><a href="refs/snapshot/1.1.x/elasticsearch-index.html">1.1.0.M6</a></td>
  | <td><a href="refs/release/1.1.0.M5/s3-index.html">1.2.0</a></td>
  | <td><a href="refs/snapshot/1.2.x/s3-index.html">1.2.1</a></td>
  | </tr>

```

which makes it difficult to find information.

Thanks,

JClaude

**Comment by paulcwarren** [comment]
Apologies, been migrating our CI from travis-ci.org to Github Actions (due to the pending shutoff of travis-ci.org and new limitations for projects built on travis-ci.com) and I messed up the doc links as part of that I think.

Thanks for the heads-up.   Should be fixed now.
