### ISSUE TITLE
Searchable<UUID> ends up with List of Strings

### ISSUE THREAD

**Issue by jcantonio** [paulcwarren/spring-content#459]
Hello!

I have a strange behaviour when using a store with Searchable with param UUID.

```
@Component
public interface SopDocumentContentStore
        extends ContentStore<SopDocument, UUID>, Searchable<UUID>, Renderable<SopDocument> {
}
```
When searching 

List<UUID> res = contentStore.search(word, paging);

res is actually a list of Strings instead of a list of UUIDs: So whenever I try to get a value from the list I have the error: 
"Parameter value element [0f3bae7d-51b4-4307-9501-548941fe2f73] did not match expected type [java.util.UUID (n/a)]".

As a work around I needed to use Strings instead.

```
@Component
public interface SopDocumentContentStore
                extends ContentStore<SopDocument, UUID>, Searchable<String>, Renderable<SopDocument> {
}
```
then remap to UUIDs

```
List<String> res = contentStore.search(word, paging);
List<UUID> resUUIDs = res.stream().map(id -> UUID.fromString(id)).collect(Collectors.toList());
List<SopDocument> docs = sopDocumentRepository.findByContentIdIn(resUUIDs);
```

Cheers!

JClaude

**Comment by paulcwarren** [comment]
All our my solr and elasticsearch tests were using String-based content-ids so I missed this and it is indeed a problem.  

I'll have a fix for this shortly.

**Comment by jcantonio** [comment]
@paulcwarren : Thank you for your support!

**Comment by paulcwarren** [comment]
Are you on Spring Content 1.1, or 1.2 @jcantonio ?
