### ISSUE TITLE
Page information when use Searchable

### ISSUE THREAD

**Issue by cxplonka** [paulcwarren/spring-content#470]
Hi,

currently when i search with "/searchContent?queryString=" i can page through the results but as information i miss the current page information(totalHits..) in the client. Is it currently possible to get this information?

And second, is it somehow possible to provide an own "SearchableImpl"?

P.S. You start a really nice project, thanks to open source it.

Greets
Christian

**Comment by paulcwarren** [comment]
Hi @cxplonka,

Thanks and thanks for giving Spring Content a try.  I hope we can work things out for you.

> currently when i search with "/searchContent?queryString=" i can page through the results but as information i miss the current page information(totalHits..) in the client. Is it currently possible to get this information?

At the moment there isn't a way to get the total hits back (for a aged search).  But I think it is easy enough to add.  As it stands currently you can [type Searchable to your own custom type](https://paulcwarren.github.io/spring-content/refs/release/1.1.0.M5/elasticsearch-index.html#_search_return_types) and there is a small set of annotations that you can add to that type to extract metadata about the search result.  I just didn't think to add hit count.  We can add that.  Are there any other pieces of search metadata that you would need?

> And second, is it somehow possible to provide an own "SearchableImpl"?
No, we can make it overridable by giving it a low precedence and ordering them (again pretty easy and should probably be done anyways) but, alternatively, you could also write your own fragment and inject the relevant client bean.

**Comment by cxplonka** [comment]
Hi @paulcwarren,

thanks for your hints. I currently point to my own controller who do the search and paging. At the end i will also need more control over the search because my UI will become search-centric at the end. My goal is to migrate my old https://github.com/cxplonka/desktop-search to the cloud.

Thanks
Christian
