### ISSUE TITLE
content-s3-spring-boot-starte and S3ObjectId

### ISSUE THREAD

**Issue by FeDLviv** [paulcwarren/spring-content#49]
Hi Paul.

Thank you so much for your hard work.

From API reference
> Ultimately, the S3 store uses instances of S3ObjectId to identify and place content. It is therefore also possible to create S3 stores using this type as the @ContentId type.

My dependencies
```
  ...
  springBootVersion = '2.0.6.RELEASE'
  contentVersion = '0.3.0'
  ...
```

```java
@Entity
@Data
public class FileEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(name = "description", length = 50)
    private String description;

    @ContentId
    private S3ObjectId contentId;
//    private String contentId;

//    @Bucket
//    private String bucket;

    @ContentLength
    private long contentLength;

    @Column(name = "mime_type", nullable = false, length = 100)
    private String contentMimeType;

}
```

But... when I change type object (String -> S3ObjectId)... I get an exception:
`org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.util.UUID] to type [com.amazonaws.services.s3.model.S3ObjectId]`

**Comment by paulcwarren** [comment]
I suspect you are hitting this because when using `S3ObjectId` as the `@ContentId` you are responsible for populating this yourself.  This isn't clear in the docs so if it turns out to be this then we'll update the docs to be clearer.  

Can you give that a go pls?

**Comment by FeDLviv** [comment]
>  @ContentId you are responsible for populating this yourself.

Ahhh... Now I understand. Thanks for your reply.

> Can you give that a go pls? Or does that not work for you in which case we might be abl to auto-generate an S3ObjectId by registering a custom S3ObjectIdReolver?

Generating unique UUID (@ContentId + String) - is fine by me.
I was just wondering about the logic of this annotation with S3ObjectId, how it works.
