### ISSUE TITLE
S3StoreConfigurer vs. deprecated S3ObjectIdResolver

### ISSUE THREAD

**Issue by martinsefcik** [paulcwarren/spring-content#495]
As `S3ObjectIdResolver` class is marked as deprecated wouldn't it be nicer to add some empty default implementation for `configureS3ObjectIdResolvers` method in `S3StoreConfigurer` interface.
So we don't have to implement this method every time during creating implementation for `S3StoreConfigurer`.

```java
public S3StoreConfigurer configurer() {
    return new S3StoreConfigurer() {

            @Override
            public void configureS3StoreConverters(ConverterRegistry registry) {
                registry.addConverter(...);
            }

===>        @Override
===>        public void configureS3ObjectIdResolvers(S3ObjectIdResolvers resolvers) {
===>            // deprecated
===>        }

        };
}
```

**Comment by paulcwarren** [comment]
Thanks for the suggestion @martinsefcik
