### ISSUE TITLE
Spring Content S3 - CannedAccessControlList support

### ISSUE THREAD

**Issue by FeDLviv** [paulcwarren/spring-content#50]
Are there any plans to support set the level of access to files?
For example:
```java
PutObjectRequest putObjectRequest = new PutObjectRequest(bucket, fileName, file)
                .withCannedAcl(CannedAccessControlList.PublicRead);
```

**Comment by paulcwarren** [comment]
If there is a requirement for it then we can definitely look into this @FeDLviv.  Are you thinking this could be another entity annotation?

**Comment by FeDLviv** [comment]
> Are you thinking this could be another entity annotation?

Even better if this field with special enum and user should be able to set access level, before saved file.

**Comment by paulcwarren** [comment]
Sorry for the inactivity on this issue.  I was thinking about this one a little more.  

If you are associating content with Spring Data Entities (and that content is being stored in S3 clearly).  I notice your example is `PublicRead` so is that content being actively accessed directly via another API (the S3 API I would presume?) in addition to the Spring Content API?  

Or is this just about setting an appropriate ACL on the content so that if it happens to be accessed it can't be messed with 

Setting an initial ACL upon creation is fine (and easy) but presumably, you would you expect the ACL to be changed appropriately on the s3 object if the ACL field on the Entity ever changed.

**Comment by FeDLviv** [comment]
> I notice your example is PublicRead so is that content being actively accessed directly via another API (the S3 API I would presume?) in addition to the Spring Content API?
This example from my project without using Spring Custom, only Spring Data and  AWS SDK for Java. User choose access level (private or public URL for read), before saved file.

> you would you expect the ACL to be changed appropriately on the s3 object if the ACL field on the Entity ever changed.
It would be nice to have this opportunity, but I would just have to set the level of access before record a file. Thereafter ignore all attempts changes value (for example - base entity without setter for this field or annotation Column with updatable = false)

**Comment by paulcwarren** [comment]
@FeDLviv, I realized that there is an option available to us today actually.  You could, I think, provide a Store customization to add a setContentACL method to your Store interface(s).  I don't know why I didn't think of this previously so I apologize.  But, anyways, you should be able to do something like this:-

```
public interface AccessControllable<T> {
	void setContentACL(T entity, AccessControlList acl);
}

@Configuration
public class StoreConfiguration {

	@Bean
	public AccessControllableImpl accessController(AmazonS3 s3) implements AccessControllable, StoreExtension {

		public void setContentACL(T entity, AccessControlList acl) {
			// use entity and s3 client to set given ACL on content object  
		}

		@Override
		public Set<Method> getMethods() {
			Class<?> clazz = Renderable.class;
			Method method;
			try {
				method = clazz.getMethod("setContentACL", Object.class, AccessControlList.class);
				Set<Method> methods = Collections.singleton(method);
				return methods;
			}
			catch (Exception e) {
                    ...
			}
			return Collections.emptySet();
		}

		@Override
		public Object invoke(MethodInvocation invocation, StoreInvoker invoker) {
			return this.setContentACL(invocation.getArguments[0], invocation.getArguments[1]);
		}
	}
}

public interface YourStore extends ContentStore<YourEntity entity, UUID>, AccessControllable {
}
```

Should allow you to call:

```
store.setContentACL(entity, acl);
```

If this would work for you then happy to add this as a "standard" extension.

**Comment by FeDLviv** [comment]
Many thanks, it's a great option.
