### ISSUE TITLE
Blob storage Azure

### ISSUE THREAD

**Issue by helderhernandez** [paulcwarren/spring-content#504]
Greetings, I am just starting 🚀  [Spring content](https://paulcwarren.github.io/spring-content/spring-content-fs-docs/) ⭐ 

I was wondering if it was possible to work with azure blob storage? I have not been able to find an example of how to do this configuration.

- pdata 1, I would like to carry out a test project in which I can store products and their images 🖼️  save them in blob storage.
- pdata 2, I apologize if I am asking my question in the wrong place and for my English (I speak Spanish and have used the translator)

**Comment by paulcwarren** [comment]
Hi @helderhernandez ,

I don't yet support Azure - just S3 and GCS atm.  That said, it shouldn't be too hard to add basic support for Azure Blob Storage if you are interested in using it.

For your use case, you would pair Spring Content with Spring Data.  Your product data would be stored in a database (of your choosing using Spring Data), and the *associated* content would be stored in blob storage (using our Content Services).  [This](https://paulcwarren.github.io/spring-content/spring-content-rest-docs/) getting started guide shows how that would look, just using filesystem storage.  But as Spring Content is an abstraction over storage, Azure would look almost identical.

HTH

**Comment by helderhernandez** [comment]
I have managed to clarify some doubts by reviewing the documentation and repositories of [spring-content-fs](https://paulcwarren.github.io/spring-content/spring-content-fs-docs/) y [spring-content-rest- docs](https://paulcwarren.github.io/spring-content/spring-content-rest-docs/) 🤓

I would like to try what you suggest, but I would like to ask for your guidance with the following concerns:
- To make my own implementation, what interface should I implement? I thought it would be the **ContentStore** interface (org.springframework.content.commons.repository.ContentStore), is this correct?

- If the previous point turns out to be true, as I tell the **ContentStore** interface to use *my implementation* instead of Filesystems, since the documentation specifies that Spring Content configures Filesystem by default, I quote ...
> [The com.github.paulcwarren: spring-content-fs-boot-starter dependency provides a filesystem based implementation of this interface and the automatic configuration of Spring Content ensures that this implementation will be used as long as FileContentRepository is @Autowired .](https://paulcwarren.github.io/spring-content/spring-content-fs-docs/#create-a-file-content-store)

- Can I use the filename as ID (to "link" with the **CONTENT_ID** of Spring Content)?
When uploading a file to Azure Blob storage, I like to rename it as follows: *random name + the extension*.

![Captura de pantalla 2021-03-10 212233](https://user-images.githubusercontent.com/47677287/110730825-c3100400-81e6-11eb-8cd7-ef8148116359.png)

But I notice that Spring Content uses CONTENT_ID to reference the file:

![Captura de pantalla 2021-03-10 212204](https://user-images.githubusercontent.com/47677287/110730817-c0adaa00-81e6-11eb-870f-cea65fc25335.png)

To my knowledge Azure Blob Storage **doesn't generate an ID** for every file uploaded to storage, so I was wondering if I could use the filename for CONTENT_ID.

I hope I have made myself understood 😆.
Thank you very much @paulcwarren for your valuable time😃.

**Comment by paulcwarren** [comment]
Hi @helderhernandez,

If you wanted to create this yourself you would need to copy something like [spring-content-gcs](https://github.com/paulcwarren/spring-content/tree/df26e8390d351bf4f378d802f65992843bb3c109/spring-content-gcs) and modify it for azure blob storage.  I suggest this one as it is the newest and simplest example.  

But, I realize that this isn't trivial so what I actually meant was that I will create this for you.  I have wanted to add Azure Storage support for a while anyway.  I have just figured out the essentials of the implementation so I don't think it will take me long to implement.

**Comment by helderhernandez** [comment]
An apology for my late answer, this news is great :partying_face:   I will be attentive to future updates of this support :smiley: 
Thank you so much for taking the time to work on the support for azure storage @paulcwarren.

**Comment by paulcwarren** [comment]
Hi @helderhernandez,

I committed an [example project](https://github.com/paulcwarren/spring-content-examples/blob/f7246b6330fec7b5998efd4f8ef7fe5ad0b62380/spring-eg-content-azure-storage/src/test/java/examples/azure/AzureExamplesTest.java) that shows how to use various flavors of azure storage.

And I updated our reference documentation to add a [reference guide for azure storage](https://paulcwarren.github.io/spring-content/refs/snapshot/1.2.x/azure-index.html).

Hopefully that helps you get started.  Please let me know if you have any issues and when you are up and running as we can work together on your requirement to append the file extension to the blob name.  Although I would also like to understand why you want to do that as it implies some of your users will be going directly to Azure and not going through your application's interface.
