### ISSUE TITLE
Spring Content S3 - Rest

### ISSUE THREAD

**Issue by jwbaldwin** [paulcwarren/spring-content#51]
Hey! 

First off, I want to say I love this project, I found it just recently and it's exactly what I need.

I'm trying to stand up a spring boot project using the s3 starter and the rest starter, but I'm having some trouble.

I've been able to POST/GET to the endpoints but as far as I can tell it's not doing anything with s3. I've configured the AmazonS3 client and defined the bucket, region, etc. 

This is what I have right now for store and repo:
```
@RepositoryRestResource
public interface DocumentRepository extends JpaRepository<Document, Long> {}

@StoreRestResource
public interface DocumentContentStore extends ContentStore<Document, Long> {}

```
The document and config are exact replicas of yours from the examples. (i.e. with all the annotaions on the entity and the @Configuration & @EnableS3Stores on the configuration class.

Can you point me towards the most up-to-date example on how to start getting CRUD operations with an s3 bucket? Or if you know something that's wrong with my set up?

Thanks in advance!

**Comment by paulcwarren** [comment]
Hi @jwbaldwin, thanks for giving Spring Content a try.

It sounds like you are not too far off.  Must be something small.  We have examples that might help [here](https://github.com/paulcwarren/spring-content-examples) and these are continuously built in travis [here](https://travis-ci.org/paulcwarren/spring-content-examples).

If all that fails, or it is easier to do so feel free to commit a small sample into your github org and point me at it.   

HTH

**Comment by jwbaldwin** [comment]
I think it's something small as well.

I think a couple questions I have might be able to answer it:
From the documentation it looks like `spring-content-rest-boot-starter` satisfies the RESTful responses, and therefore I don't need `spring-boot-starter-data-rest`. But as of now, without the latter, all I get are 404's, did I miss an update that made it required again?

Also, when working locally, POSTing to an endpoint that was rolled by spring-content (i.e. "/documents") should actually go and store the item in S3 (assuming i'm using the content-s3 of course), right? Right now it succeeds, and I can go to `documents/1` and see it, or hit `documents/` and see all of the items, but nothing is *actually* being stored in S3, my guess is it's storing in hsql? Do I need to make calls to the repository in order to actually store in s3? I thought S3 + REST would handle that for me?

Thanks in advance, I appreciate the help!

If I can't get it after this I'll throw it up and point you to it! :)

**Comment by paulcwarren** [comment]
`spring-content-rest-boot-starter` has always just added content-related endpoints, so you need `spring-boot-starter-data-rest` if you want to entity-related endpoints.  Then `spring-content-s3-boot-starter` if you want to store in S3.  Content won't get stored in HSQL unless you have `spring-content-jpa-boot-starter` dependency.

If you are trying to associate a single piece of content with an entity class `Document` (by placing an `@ContentId` on the entity) and you have used the `@RepositoryRestResource` and `@StoreRestResource` "as-is" then both will try and handle "{repository|store}/documents/{id}" requests.  Your client must, therefore, use the `Content-Type` header to direct the request to either the Spring Data or Content endpoint.   Or you can use  `@StoreRestResource(path='documentsContent')` instead to deconflict them completely and you don't have to worry about it as much.  That said, if you want to use the `@MimeType` annotation to capture the content-type or use Spring Content Renditions to transform content from one format to another then you have to want to send the content-type anyways.

Lastly, to store and entity and then associate content with it is two separate requests.  The first an `application/json+hal` POST request to `/documents` creates the Spring Data Entity.  The second a multipart-formdata PUT request to `/documents/{id}` with a `file` field and the content associates that content with your entity.  

Not sure if that helps, or not.

Feel free to upload a sample that shows your problem and I am sure we can figure it out.

**Comment by jwbaldwin** [comment]
This helped clear things up immensely. Namely the way the entity and content interact with each other.

Thanks a ton for the assistance. I'll mark this is closed!

**Comment by paulcwarren** [comment]
No problem.  Feel free to re-open or raise another issue if you run into anything else.
