### ISSUE TITLE
Content links missing when using Spring Data REST projections

### ISSUE THREAD

**Issue by tgeens** [paulcwarren/spring-content#513]
When using [projections](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#projections-excerpts) with the `@Projection` annotation in Spring Data REST, the `content` association in the HATEAOS `_links` section is missing.

That is because Spring Content looks for fields annotated with `@ContentId` to generate the link in [ContentLinksResourceProcessor](https://github.com/paulcwarren/spring-content/blob/1.2.x/spring-content-rest/src/main/java/internal/org/springframework/content/rest/links/ContentLinksResourceProcessor.java).

But projections have no fields, only methods. Putting the `@ContentId` annotation on a `String getContentId()` method in the projection interface does not help.

I think this could be resolved by not only considering the fields, but also looking at the `propertyDescriptor.getReadMethod()` when checking if the `@ContentId` annotation is present.

Pseudo code:

```
var propertyDescriptor = new BeanWrapperImpl(object).getPropertyDescriptors()[index];
if (AnnotationUtils.findAnnotation(propertyDescriptor.getReadMethod(), ContentId.class) != null) {
    ...
}
```

@paulcwarren would you consider such a change ?

**Comment by paulcwarren** [comment]
We are missing a test case in this area.  Hence, this has snuck through.  

But absolutely @tgeens.  From what you describe that sounds like a reasonable fix to me.
