### ISSUE TITLE
NoSuchMethodError with JPA and Vaadin

### ISSUE THREAD

**Issue by JoeBrig** [paulcwarren/spring-content#56]
When adding Spring Data and Spring Content JPA to a Vaadin application, created from :
     https://vaadin.com/start/latest/project-base-spring

The application returns the below errors.  The easiest way to receive the error is to navigate to a Route that doesn't exist. I tried different version of Vaadin and Spring Content, H2, and MySql, with the same errors. 

Using Vaadin 12.0.3
Spring content 0.4.0.  
Spring Boot: 2.1.0.RELEASE

Attached is a sample project.
[sc_error.zip](https://github.com/paulcwarren/spring-content/files/2704209/sc_error.zip)

Errors:
2018-12-21 15:27:20.191 ERROR 22343 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Servlet execution threw an exception] with root cause

java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
	at com.vaadin.flow.router.RouteNotFoundError.readHtmlFile(RouteNotFoundError.java:75) ~[flow-server-1.2.3.jar:1.2.3]

**Comment by paulcwarren** [comment]
Hi @JoeBrig, the only way I could reproduce this error was to request a mapping/route that doesn't exist.  I tracked it down to a really old version of apache commons io.  We had a dependency on 1.3.1!  We updated this to 2.6.

You can use `0.6.0-SNAPSHOT`, or, if you wish to stay on a release, the workaround on `0.4.0` or `0.5.0` is to create a dependency on the new version and exclude the old version from `spring-content-jpa`, as in the following:

```
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
        </dependency>

        <dependency>
            <groupId>com.github.paulcwarren</groupId>
            <artifactId>spring-content-jpa-boot-starter</artifactId>
            <version>0.5.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

FYI, in your sample application, I noticed that you had a dependency on `spring-content-autoconfigure` and on `spring-content-jpa`.  in cae you didnt notice it already, we do have a boot starter for jpa `spring-content-jpa-boot-starter`.

Anyways, let me know if you have any more issues.
