### ISSUE TITLE
ResourceHttpRequestHandler warnings

### ISSUE THREAD

**Issue by jshailes** [paulcwarren/spring-content#58]
After adding `spring-content-fs-boot-starter` and `spring-content-rest-boot-starter` (version 0.5.0) to my a spring boot 2.0.4 project I receive some warnings on application start. 

The warnings are:

	o.s.w.s.r.ResourceHttpRequestHandler - Locations list is empty. No resources will be served unless a custom ResourceResolver is configured as an alternative to PathResourceResolver.

	f.a.AutowiredAnnotationBeanPostProcessor - Inconsistent constructor declaration on bean with name 'contentPropertyCollectionRestController': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public internal.org.springframework.content.rest.controllers.ContentPropertyCollectionRestController(org.springframework.context.ApplicationContext,org.springframework.content.commons.storeservice.ContentStoreService,internal.org.springframework.content.rest.mappings.StoreByteRangeHttpRequestHandler)

	f.a.AutowiredAnnotationBeanPostProcessor - Inconsistent constructor declaration on bean with name 'contentPropertyRestController': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public internal.org.springframework.content.rest.controllers.ContentPropertyRestController(org.springframework.context.ApplicationContext,org.springframework.content.commons.storeservice.ContentStoreService,internal.org.springframework.content.rest.mappings.StoreByteRangeHttpRequestHandler)

I've tried upgrading to spring boot 2.1.1 and this causes the application not to start:

	***************************
	APPLICATION FAILED TO START
	***************************

	Description:

	The bean 'contentRestExceptionHandler', defined in class path resource [org/springframework/content/rest/config/RestConfiguration.class], could not be registered. A bean with that name has already been defined in URL [jar:file:/home/user/.m2/repository/com/github/paulcwarren/spring-content-rest/0.5.0/spring-content-rest-0.5.0.jar!/internal/org/springframework/content/rest/controllers/ContentRestExceptionHandler.class] and overriding is disabled.

	Action:

	Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Setting `spring.main.allow-bean-definition-overriding=true` in `application.properties` resolves the issue with application start on `2.1.1` however the following warning still remains:

	o.s.w.s.r.ResourceHttpRequestHandler - Locations list is empty. No resources will be served unless a custom ResourceResolver is configured as an alternative to PathResourceResolver.

**Comment by jshailes** [comment]
Just some further info. I've tried upgrading to spring-boot 2.1.1 from 2.0.4 and this has led to the application failing to start:


	***************************
	APPLICATION FAILED TO START
	***************************

	Description:

	The bean 'contentRestExceptionHandler', defined in class path resource [org/springframework/content/rest/config/RestConfiguration.class], could not be registered. A bean with that name has already been defined in URL [jar:file:/home/jim/.m2/repository/com/github/paulcwarren/spring-content-rest/0.5.0/spring-content-rest-0.5.0.jar!/internal/org/springframework/content/rest/controllers/ContentRestExceptionHandler.class] and overriding is disabled.

	Action:

	Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

**Comment by jshailes** [comment]
I've created an example project highlighting the issue I'm experiencing - [http://picosoft.co.uk/spring-content-demo.zip](http://picosoft.co.uk/spring-content-demo.zip)

**Comment by paulcwarren** [comment]
Hi @jshailes.  Thanks for giving Spring Content a try and raising these issues.  

Seems like there are two issues here.  1. Warnings on start-up and 2. Re-defined spring content beans.  

Looks like:- 
1.  the warnings are just incorrectly configured constructors in our Spring Content REST layer.  Those should be easily fixable.  No problem there.  The `ResourceHttpRequestHandler` warning looks to be from our StoreByteRangeHttpRequestHandler which is used directly by our rest controllers.   We should probably override the afterPropertiesSet to remove the warning - or possibly use the resource handler more correctly.
2. we dont officially support spring boot 2.1.x yet.    This is slated for our next release 0.6.0 though.  However, that re-defined bean issue for `contentRestExceptionHandler` is already fixed on head (`0.6.0-SNAPSHOT`).  You can grab that if you would like by adding the following repo to your `pom.xml`:
```
	<repositories>
		<repository>
			<id>snapshots</id>
			<name>nexus</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
```

Anyways, we'll take care of these.

**Comment by jshailes** [comment]
Great, thanks Paul

**Comment by paulcwarren** [comment]
Re-opening to make sure we schedule a story to fix the reported warnings.
