### ISSUE TITLE
Support for changing the base uri

### ISSUE THREAD

**Issue by jshailes** [paulcwarren/spring-content#59]
It would be really useful if spring content resources could be served up from a [non-root URI](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#getting-started.changing-base-uri), so rather than accessing via '/files/file-uuid' it could be from '/api/files/my-my-uuid'.

**Comment by paulcwarren** [comment]
Thanks @jshailes .  As discussed we'll try and get this into 0.6.0.

**Comment by vincentmathis** [comment]
I've tried both 
`spring.content.rest.baseUri=/api
spring.content.rest.base-uri=/api`
in application.properties
But the endpoints is still using the root path.

**Comment by paulcwarren** [comment]
Thanks for raising this @vincentmathis.  This is indeed a bug.  There is a gap in our testing.  As a workaround, you can create a `ContentRestConfigurer` bean and set your base path via that.  But we'll fix the spring boot property.  Re-opening.

**Comment by paulcwarren** [comment]
If you would like to try this before 0.10.0 is released.  You can grab the latest snapshot (`0.10.0-SNAPSHOT`) by adding the following repository to your POM:

```
<repository>
	<id>snapshots</id>
	<name>nexus</name>
	<url>https://oss.sonatype.org/content/repositories/snapshots</url>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```
