### ISSUE TITLE
getting S3StoresRegistrar does not define or inherit an implementation error

### ISSUE THREAD

**Issue by mmoukimou** [paulcwarren/spring-content#591]
I am trying to implement Spring content to use with AWS S3. After configuring everything, and running the Spring boot application i keep getting this error: java.lang.AbstractMethodError: Receiver class internal.org.springframework.content.s3.config.S3StoresRegistrar does not define or inherit an implementation of the resolved method 'abstract java.lang.Class[] getIdentifyingTypes()' of abstract class org.springframework.content.commons.config.AbstractStoreBeanDefinitionRegistrar.

Any clue what might be the cause of this? am i missing something somewhere?

**Comment by paulcwarren** [comment]
Might be mismatched Spring Content library versions?  

`spring-content-commons` used to have an abstract method called `getIdentifyingTypes` and from the error the class `S3StoresRegistrar` from `spring-content-s3` doesn't implement that method.

Perhaps your s3 library is older than your commons library, or newer.   FYI yhey should be versioned matched.

How are you declaring your dependencies?

**Comment by mmoukimou** [comment]
It was indeed a version mismatch. This issue is fixed now. Thank you.
