### ISSUE TITLE
spring-content-s3-boot-starter drags spring-data-jpa dependency

### ISSUE THREAD

**Issue by neVERberleRfellerER** [paulcwarren/spring-content#61]
In my use case 0.4.0 worked fine, but 0.5.0 now drags spring-data-jpa into classapth, but I am not using spring-data-jpa (I am not usiing spring-data directly at all) which results in NoClassDefFound when autoconfiguration kicks in (it can't find javax/persistence/EntityManagerFactory).

The chain is:
spring-content-s3-boot-starter -> spring-content-s3 -> spring-content-commons -> spring-versions-commons -> spring-data-jpa

At the end, non-optional spring-data-jpa dependency is present. Is it intentional?

**Comment by paulcwarren** [comment]
@neVERberleRfellerER.  Thanks for raising this as an issue and I apologize for the tardy response times.  We can take a look at this.  When we add the locking and versioning feature I assume we created this.  Will take a look and see if we can remove it for you.

**Comment by paulcwarren** [comment]
Hi @neVERberleRfellerER, the idea of Spring Content is to be an abstraction layer over the storage, just like Spring Data is the abstraction layer over the database.  So, you can use any JPA database with filesystem storage, or S3 for example.  You wouldn't, and are not, forced to use BLOBs (i.e. SC JPA).  Some seem to belong together Spring Data Mongo and Spring Content Mongo.  

So your original assessment is correct.  If you are not using "locking and versioning" then it shouldn't be pulling in spring-data-jpa for sure.  That said, "locking and versioning" is a new feature and ONLY supports JPA right now.  The design of this feature should match the goals of the Spring Data/Spring Content project but might not be quite correct right now but might not be quite there.  We'll continue to iterate on it.
