### ISSUE TITLE
404 when running on Java 9, or above

### ISSUE THREAD

**Issue by netwrkx** [paulcwarren/spring-content#621]
Thanks for awesome work on this project..

I want to add spring-content to an existing application but i got this error.
I disabled some of my configuration and i found that when when mvcConfig is in use, i get 404 but when i remove the mvcConfig file, spring-content works

Error message
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Aug 26 12:31:35 WAT 2021
There was an unexpected error (type=Not Found, status=404).
```
console log
`o.s.web.servlet.PageNotFound             : No mapping for GET /videos/Kevon-Carter.mp4`

mvcConfig file
```
@EnableWebMvc
@Configuration
public class MvcConfig implements WebMvcConfigurer {

    @Override
    public void addInterceptors(final InterceptorRegistry registry) {
        registry.addInterceptor(new LoggerInterceptor());
    }
}
```
VideoStore file
```
@StoreRestResource(path = "/videos")
public interface VideoStore extends Store<String> {

}
```

plugins
```
<dependency>
	<groupId>com.github.paulcwarren</groupId>
	<artifactId>spring-content-fs-boot-starter</artifactId>
	<version>1.2.4</version>
</dependency>
 <dependency>
	<groupId>com.github.paulcwarren</groupId>
	<artifactId>spring-content-rest-boot-starter</artifactId>
	<version>1.2.4</version>
</dependency>
```

**Comment by paulcwarren** [comment]
Spring Content doesn't assume a location for storage.  It has to be told.  Did you see the bean set up in the [configuration](https://github.com/paulcwarren/issue-621/blob/b3210cbf1bd7aad13eb7c13192c496c4a52ee49d/src/main/java/com/example/issue621/Issue621Application.java#L39) and modify to point to the location where you store your videos (which sounds like the root of your project)?

**Comment by netwrkx** [comment]
@paulcwarren i've updated the configuration as follows but i still get 404. is there something i'm doing wrong

```
@Configuration
@EnableFilesystemStores
public class EnableFilesystemStoresConfig {
	@Bean
	FileSystemResourceLoader fileSystemResourceLoader() {
		return new FileSystemResourceLoader(new FileSystemResource("videos").getFile().getAbsolutePath());
	}
}
```

**Comment by paulcwarren** [comment]
I would put some debug in that bean initialization to double check where `new FileSystemResource("")` actually is.  Is it actually `E:\rpi\1\issue-621`?  

I am not sure why you want to use a `FileSystemResource` there.  It's just a file path.

`return new FileSystemResourceLoader("E:/rpi/1/issue-621");`

might be more obvious.    Regardless, wherever that ends up being is where you video content should be put.

**Comment by netwrkx** [comment]
@paulcwarren i really appreciate your patience & support. currently i have this

```
	    @Bean
	    public File filesystemRoot() {
	        try {
	            String fileName = "E:/rpi/1/issue-621";
	            Path path = Paths.get(fileName);
	            return Files.createDirectories(path).toFile();
            } catch (IOException ioe) {
                int i=0;
            }
	        return null;
	    }

	    @Bean
	    public FileSystemResourceLoader fileSystemResourceLoader() {
	        return new FileSystemResourceLoader(filesystemRoot().getAbsolutePath());
	    }
```

`http://localhost:8080/videos/Kevon-CarterV1.mp4`

i still got error 404
`There was an unexpected error (type=Not Found, status=404).`

**Comment by paulcwarren** [comment]
Looks ok to me.   There is a change an IOException is getting eaten there, of course.  So, if you know `E:/rpi/1/issue-621/` definitely exists then you could refactor it to be even simpler - thus ruling the eaten exception:

```
            @Bean
	    public File filesystemRoot() throws IOException {
	            return new File("E:/rpi/1/issue-621");
	    }
```

And the `E:/rpi/1/issue-621/Kevon-CarterV1.mp4` also definitely exists, I presume?

**Comment by netwrkx** [comment]
@paulcwarren same error 404, 
file exist at `E:/rpi/1/issue-621/videos/Kevon-Carter.mp4`

```
		@Bean
	    public File filesystemRoot() throws IOException {
	        return new File("E:/rpi/1/issue-621");
	    }
	
		@Bean
		FileSystemResourceLoader fileSystemResourceLoader() throws IOException {
			return new FileSystemResourceLoader(filesystemRoot().getAbsolutePath());
		}
```

**Comment by paulcwarren** [comment]
OK.  Can you submit a PR of your changes back to that sample repo so I can try the latest too please.

**Comment by netwrkx** [comment]
@paulcwarren PR submitted

**Comment by paulcwarren** [comment]
OK. I pulled your PR.  Changed `E:/rpi/1/issue-621` to `/tmp/issue-621`.   Put a video file called `Kevon-CarterV1.mp4` in `/tmp/issue-621` and ran this curl:

`curl -v --output - http://localhost:8080/videos/Kevon-CarterV1.mp4`
(and also visited the URL in my browser) 

And I get the video content just fine.

Are you seeing any errors in the console at all?

**Comment by netwrkx** [comment]
@paulcwarren i updated the code to use `String fileName = "/tmp/issue-621";`
but when i placed the video file in /tmp/issue-621 directory i got an error 500 but when i placed the video file in /tmp/issue-621/videos directory, i got error 404

`error 500`
![Capture23](https://user-images.githubusercontent.com/5035044/131854914-14252553-3d0e-4df4-97d6-5a541c54ea55.PNG)
![Capture24](https://user-images.githubusercontent.com/5035044/131854940-053026b2-9a16-4ac7-9f1e-6c6f7c9302f5.PNG)

**Comment by paulcwarren** [comment]
Ah, there is your problem.  Java 9 disables access to javax packages.  You can use [this workaround](https://newbedev.com/eclipse-java-lang-noclassdeffounderror-javax-activation-datahandler) if running on Java 9, or above.


Please note, I am on a mac and your are on windows so using `/tmp/issue-621` is never going to work for you.

**Comment by paulcwarren** [comment]
Did this workaround work for you @netwrkx ?

**Comment by netwrkx** [comment]
@paulcwarren yes, thanks. I really appreciate your support
