### ISSUE TITLE
Question regarding file save path

### ISSUE THREAD

**Issue by mato-stanic** [paulcwarren/spring-content#63]
Hello,

We have started using this library in our new project and we were wondering is it possible to save every file in different directory? We have defined "spring.content.fs.filesystemRoot" in our application.properties as "/opt/files", and we would like for each file to have its own parent folder inside filesystemRoot. For example, if UUID is "78e604ec-391c-47c4-8014-db3430796dae", the path to file would be "/opt/files/78e604ec/78e604ec-391c-47c4-8014-db3430796dae" (the parent folder should be root + first part of UUID).

Thank you in advance for your answer!

**Comment by paulcwarren** [comment]
Hi @mato-stanic yes this is possible.  File-system storage supports [Storage Customization](https://paulcwarren.github.io/spring-content/refs/snapshot/fs-index.html#_filesystem_content_stores).  

Stores are really just Spring ResourceLoaders and therefore look up content via a String-based location.  You can register a Spring Converter that converts UUID to String.  The filesystem store will use this to convert your content's UUID-based ID into a String-based location.  You can apply whatever transformation your would like.  So it would look something like this:

```
@Configuration
public class FilesystemStoreConfiguration {

	@Bean
	public FilesystemStoreConfigurer configurer() {
		return new FilesystemStoreConfigurer() {

			@Override
			public void configureFilesystemStoreConverters(ConverterRegistry registry) {
				registry.addConverter(new Converter<UUID, String>() {

					@Override
					public String convert(UUID source) {
						String strUUID = source.toString();
						String tld = strUUID.substring(0, strUUID.indexOf("-") - 2);
						return String.format("/%s/%s", tld, strUUID);
					}
				});
			}
		};
	}
}
```

Code not tested so provide your own implementation for `convert`.  Just trying to show how it is done.

HTH

**Comment by mato-stanic** [comment]
Thank you for a great and fast response :)
