### ISSUE TITLE
PlacementService not using custom ContentID converter

### ISSUE THREAD

**Issue by miguelaferreira** [paulcwarren/spring-content#64]
Hi Paul,

Congratulations on a very nice project you created.
I've decided to give it a go for a system I'm building but I cannot seem to get the `PlacementService` to use my custom `@ContentId` converter.

I have an entity
```java
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Document {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;
    private String hash;
    private String originalName;

    @ContentId
    private UUID contentId;
    @ContentLength
    private Long contentLen;
    @MimeType
    private String mimeType = "application/pdf";
}
```

And a configuration class that defines a `S3StoreConfigurer` to add my custom converter
```java
@Configuration
public class S3StoreConfiguration {

    private String s3ObjectKeyPrefix;

    @Autowired
    public S3StoreConfiguration(@Value("${app.s3ObjectKeyPrefix}") final String s3ObjectKeyPrefix) {
        this.s3ObjectKeyPrefix = s3ObjectKeyPrefix;
    }

    @Bean
    public S3StoreConfigurer configurer() {
        return new S3StoreConfigurer() {

            @Override
            public void configureS3StoreConverters(ConverterRegistry registry) {
                // Do not replace anonymous class with lambda otherwise spring won't be able to determine source type <S> and target type <T> for your Converter
                registry.addConverter(new Converter<UUID, String>() {

                    @Override
                    public String convert(final UUID source) {
                        return String.format("/%s/%s", s3ObjectKeyPrefix, source.toString());
                    }
                });
            }

            @Override
            public void configureS3ObjectIdResolvers(S3ObjectIdResolvers resolvers) {
                // deprecated
            }
        };
    }
}
```
As you can see what I want is to inject a default object key prefix in all the objects in my bucket.
However, when I run this I still get the `UUID.toString()` as a key.
I've debugged my code and it seems that the `PlacementService` is always using a generic converter while I do see it holds a reference to my custom converter in the list of converters.

I did implement a resolver (which seem deprecated in favour of converters) and that worked when storing the objects but not when retrieving them.

Do you have any idea of what am I doing wrong?

**Comment by miguelaferreira** [comment]
With some more fiddling I was eventually able to write a converter that worked.
I had to make a converter from my domain entity to s3ObjectId and make sure to inject a new random UUID whenever the contentId field is null.

```java
@Bean
    public S3StoreConfigurer configurer() {
        return new S3StoreConfigurer() {

            @Override
            @SuppressWarnings("Convert2Lambda")
            public void configureS3StoreConverters(ConverterRegistry registry) {
                // Do not replace anonymous class with lambda otherwise spring won't be able to determine source type <S> and target type <T> for your Converter
                registry.addConverter(new Converter<Document, S3ObjectId>() {

                    @Override
                    public S3ObjectId convert(final Document source) {
                        UUID contentId = source.getContentId();
                        if (contentId == null) {
                            final UUID randomUUID = UUID.randomUUID();
                            source.setContentId(randomUUID);
                            contentId = randomUUID;
                        }
                        return new S3ObjectId(s3BucketName, String.format("/%s/%s", s3ObjectKeyPrefix, contentId.toString()));
                    }
                });
            }

            @Override
            public void configureS3ObjectIdResolvers(S3ObjectIdResolvers resolvers) {
                // deprecated
            }
        };
    }
```

**Comment by paulcwarren** [comment]
Hi @miguelaferreira thanks for raising the issue.

Apologies, this feature did just change.  We did, as you say, deprecate `S3ObjectIdResolver`s in favor of Spring `Converter`s.  The docs around this feature are also a little weak.  

You should be able to register a `Converter<S3ObjectId, String>`.  This is the last conversion that will be tried in order to convert the key of the S3ObjectId into a Resource location.  Spring Content Stores are really just generic ResourceLoaders and load the Resource using the standard `getResource(String location)` method. 

But you should also be able to register a `Converter<YourEntity, S3ObjectId`> that allows you to do things like use a field on your entity to determine bucket location.

You should also be able to register a `Converter<UUID,S3ObjectId>` as well (where UUID is the type of the @ContentId field to manipulate the key.

Sounds like you opted for the seconded use case there.  I am a bit confused by you needed to handle the null case though.  What version of Spring Content are you using?

**Comment by paulcwarren** [comment]
I committed a fix for the null case that you highlighted. That fix will be in the upcoming release 0.7.0.  It is on the [SNAPSHOTs](https://oss.sonatype.org/content/repositories/snapshots) if you would like to consume it.

**Comment by miguelaferreira** [comment]
Hi Paul,

Thank you so much for the quick reaction. I will be happy to test the snapshot and get back to you.
Regarding your question about spring versions I'm building against springBootVersion = '2.1.2.RELEASE'

**Comment by paulcwarren** [comment]
OK.  You should be able to grab that by updating your dependency version to 0.7.0-SNAPSOT and adding the following repository (assuming you are using maven):

```
	<repositories>
		<repository>
			<id>snapshots</id>
			<name>nexus</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
```

**Comment by miguelaferreira** [comment]
Thanks again Paul.
I've pulled in version `0.7.0-SNAPSHOT` commented out my handing of the null case and my unit tests are happy.

I'm closing the ticket now since the issue is solvable.
