### ISSUE TITLE
Spring content throwing 404 on REST endpoints when not spe

### ISSUE THREAD

**Issue by thijslemmens** [paulcwarren/spring-content#643]
**Describe the bug**
404 Response code is returned with Spring Content related error message on URL's that are not content related.

**To Reproduce**
1. Write a @RepositoryRestResource and @StoreRestResource for an Entity (/api/archiveDocuments)
2. Add a controller that exposes a URL that contains a resource URL in the path (POST /api/archiveDocuments/{uuid}/softDelete)
3. Launch a request to that enpoint without specifying header "Accept: application/json"
4. 404 code is returned: internal.org.springframework.content.rest.controllers.ResourceNotFoundException: Resource not found!

**Expected behavior**
Run the code in the Controller

Full message:

{
  "timestamp": "2021-10-13T15:22:12.716+00:00",
  "status": 404,
  "error": "Not Found",
  "trace": "internal.org.springframework.content.rest.controllers.ResourceNotFoundException: Resource not found!\n\tat internal.org.springframework.content.rest.controllers.resolvers.PropertyResolver.getContentPropertyDefinition(PropertyResolver.java:191)\n\tat internal.org.springframework.content.rest.controllers.resolvers.PropertyResolver.resolve(PropertyResolver.java:49)\n\tat internal.org.springframework.content.rest.controllers.StoreHandlerMethodArgumentResolver.resolveArgument(StoreHandlerMethodArgumentResolver.java:103)\n\tat internal.org.springframework.content.rest.controllers.ResourceHandlerMethodArgumentResolver.resolveArgument(ResourceHandlerMethodArgumentResolver.java:38)\n\tat org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:665)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:750)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)\n\tat org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n",
  "message": "Resource not found!",
  "path": "/api/archiveDocuments/3ac8c379-9f7c-4e19-977b-f497e07792cb/softDelete"
}

**Comment by paulcwarren** [comment]
Thanks @thijslemmens.  Much appreciated.  Will look into soonest.

**Comment by paulcwarren** [comment]
Hi @thijslemmens,

I  have a couple of questions.  

Custom controllers are evaluated before the content controllers.   I also note the /api base path.  How are you defining this customer controller and making it base path  aware?

**Comment by paulcwarren** [comment]
Thanks for the info @tgeens 

As I am sure you figured out the store controller is handling the request.  When being matched against the incoming request, the content controller sits ahead of the repository controllers AND also has a very aggressive request mapping and so it handles the request.  

There are several approaches to avoiding this: 
1. setting the content-type header (not accept); there is a get out clause built into the content controllers where they will skip, in this case, POSTs with `application/json` mime type.   this is actually dumb and I have wanted to remove this code for a while.  I wouldn't recommend using this, honestly.  I am determined to get rid of it at some point.
1.  Use a `ContentRestConfigurer` bean to set a different base path; this would entail using the `spring.data.rest.base-uri=api` and `spring.content.rest.base-uri=contentApi` instead of `server.servlet.context-path` to put the rest controller under /api and the content controller under /contentApi.  This will deconflict them and the store controller wont grab to the requests to softDelete.
1. Make the soft delete controller a `@Controller` or `@RestController` instead of a `@RepositoryRestController` as this will place it ahead of the content controller.

Out of the 3 I would recommend option 2 especially if your clients are following links to content in the hypermedia responses.  But interested to hear your thoughts.

**Comment by thijslemmens** [comment]
Thanks Paul

I can confirm that switching to @Controller works.
Option 1 is what we are using right now, and we will keep that as well. 
Option 2 is a possibility, but it feels a bit less elegant to me. Part of our permissions are based on the path, so changing the path would also impact those permissions.

kind regards

Thijs

**Comment by paulcwarren** [comment]
Fixed with [8527975](https://github.com/paulcwarren/spring-content/tree/852797565589eafbc1e8b107cdd74ec4fb9aef57)
