### ISSUE TITLE
Blobs from Content Store are not deleted from the database when using spring-content-jpa together with PostgreSQL

### ISSUE THREAD

**Issue by MartinWilhelm** [paulcwarren/spring-content#659]
Hi,

we are using spring-content-jpa in combination with spring-content-cmis and a PostgreSQL database.
That means all content store entries are stored as BLOBs in our database.
PostgreSQL doesn't store BLOBs directly in the tables which are used by the application (in our case the content store table BLOB). Instead it only stores a OID there. The BLOB itself is stored in the catalog pg_largeobject (https://www.postgresql.org/docs/9.0/catalog-pg-largeobject.html)
Unfortunately, when we remove the content from the content store, then only the entry from the BLOB table is deleted. The BLOB itself remains available in the pg_largeobject catalog table.
The entries from the the catalog tables pg_largeobject and pg_largeobject_metadata should be removed too. 
This is possible by calling "SELECT lo_unlink(OID)" (https://www.postgresql.org/docs/9.4/lo-funcs.html). But this isn't triggered from spring-content-jpa.

Regards
Martin

**Comment by paulcwarren** [comment]
Thanks for the bug report @MartinWilhelm ,

I have submitted a PR with the fix.
