### ISSUE TITLE
Impossible to delete Folder when using spring-content-cmis

### ISSUE THREAD

**Issue by MartinWilhelm** [paulcwarren/spring-content#660]
Hi,

we are using spring-content-jpa in combination with spring-content-cmis.
In our application we want to cleanup empty folders and remove them from the Content Store.

Hence we first select the Folder using the CMIS Session:

`Folder  folder = (Folder) session.getObject(od);`

Then we call 

`folder.delete();`

This triggeres (after a lot of steps) the deleteObject method from the CmisServiceBridge class from spring-content-cmis:

```
	@Transactional
	public void deleteObject(CmisRepositoryConfiguration config,
			String objectId,
			Boolean allVersions,
			ExtensionsData extension) {

		Object object = getObjectInternal(config, objectId, Collections.EMPTY_SET, false, IncludeRelationships.NONE,
				"", false, false, extension);
		if (object != null) {
			config.cmisDocumentStorage().unsetContent(object);
			config.cmisDocumentRepository().delete(object);
		}
	}
```

This methods triggers a call of the delete method from the document repository (not from the folder repository).

```
@Override
    public void delete(T entity) {

      Authentication authentication = auth.getAuthentication();
        if (authentication == null || !authentication.isAuthenticated()) {
            throw new SecurityException("no principal");
        }

        Object id = this.getId(entity);
        if (id == null) return;

        if (!isHead(entity)) {
            throw new LockingAndVersioningException("not head");
        }

        boolean relock = false;
        if (lockingService.lockOwner(id) != null && !lockingService.isLockOwner(id, authentication)) {
            throw new LockOwnerException("not lock owner");
        } else if (lockingService.lockOwner(id) != null && lockingService.isLockOwner(id, authentication)) {
            relock = true;
        }

        Object ancestorRootId = getAncestralRootId(entity);
        Object ancestorId = getAncestorId(entity);

        T ancestor = null;
        if (ancestorId == null) {
            ancestorId = ancestorRootId;
        }

        if (ancestorId != null) {

            ancestor = (T) em.find(entity.getClass(), ancestorId);

            Principal lockOwner = null;
            if ((lockOwner = lockingService.lockOwner(ancestorId)) != null && !Objects.equals(authentication.getName(),lockOwner.getName())) {
                throw new LockOwnerException(format("Not lock owner %s", ancestorId));
            } else if (lockOwner == null && relock) {
                lockingService.lock(ancestorId, authentication);
            }

            BeanUtils.setFieldWithAnnotation(ancestor, SuccessorId.class, null);

            if (ancestorRootId.equals(ancestorId)) {
                BeanUtils.setFieldWithAnnotation(ancestor, AncestorRootId.class, null);
            }
        }

        lockingService.unlock(id, authentication);

        em.remove(em.contains(entity) ? entity : em.merge(entity));
    }
```

There the isHead method checks whether the version is the head version:

```
    protected <T> boolean isHead(T entity) {
        boolean isHead = false;
        if (BeanUtils.hasFieldWithAnnotation(entity, SuccessorId.class)) {
            return BeanUtils.getFieldWithAnnotation(entity, SuccessorId.class) == null;
        }
        return isHead;
    }
```

The folders are unversioned, so this check fails and a LockingAndVersioningException is thrown above.

But even if this check wouldn't fail, the deletion would still fail, because the document repository will not find the folder. 
Instead, the CMIS fodler repository has to be used for deletion.

So from our point of view, there should be a check within the delete Methode from the class CmisServiceBridge:

if class of object is annotated with @CmisDocument, then 
`config.cmisDocumentRepository().delete(object);`
else if class of object object is annotated with @CmisFolder, then
`config.cmisFolderRepository().delete(object);`

Regards
Martin

**Comment by paulcwarren** [comment]
Thanks @MartinWilhelm, thanks for giving the CMIS module a try.   I will look into this soonest for you.  

Just to pre-warn you though I do consider this module alpha at the moment.   But, as such, will try to prioritize any issues that you find.

So, just to be clear, as it is helpful to understand the context.  It sounds like you are using CMIS but not its versioning and therefore your Spring Content stores are also not extending `LockingAndVersioiningRepository`?   Is that right?  You are basically just performing CRUD operations on documents and folders via the CMIS API?

**Comment by MartinWilhelm** [comment]
Hi @paulcwarren,

no, our Spring Content stores for our documents are extending the LockingAndVersioningRepository. Just the folders aren't.
We are uploading and unzipping zip-files and storing der content. Later we plan to support mutliple (customer specific) storage systems. E.g. a customer might want to store there contents on an S3, then it should be possible to do this be just switching the configuration. The zip-files contain files and folders with a predefined directory tree. Different zip-files are disjunct. We have to support the deletion of the whole content of such zip-files from the content store. Hence we go through the tree and delete all documents and folders from the CMIS system. But the deletion of the folders fails as described above. (The deletion of the documents works).
