### ISSUE TITLE
Deletion of all document version only deletes head version

### ISSUE THREAD

**Issue by MartinWilhelm** [paulcwarren/spring-content#663]
Hi,

we are using spring-content-jpa in combination with spring-content-cmis.
In our application we want delete documents with multiple version and remove them from the Content Store.

When I call `doc.delete(true);` for a `Document doc`, then I would expect that all versions of this document are deleted from the database. Unfortunately only the head version is removed. It seems whether the `allVersions = true` option is ignored.

Regards Martin

**Comment by paulcwarren** [comment]
Thanks @MartinWilhelm.  If I recall, this was a deliberate omission for the initial version but if you need this feature we should add.  Will look tomorrow.
