### ISSUE TITLE
Update Spring versions

### ISSUE THREAD

**Issue by timsanwald** [paulcwarren/spring-content#68]
Hi,
it would be nice if this would be updated to spring-boot 2.1 and the new spring-cloud releases.

**Comment by paulcwarren** [comment]
@timsanwald. Thanks for raising the issue.  For sure it is overdue.  Will take care of this in the 0.7.0 release.

**Comment by paulcwarren** [comment]
Currently blocked from upgrading to Spring Boot 2.1.3.RELEASE due to [this Spring Data Lovelace bug](https://jira.spring.io/browse/DATACMNS-1487).
