### ISSUE TITLE
Easy swtiching between content store

### ISSUE THREAD

**Issue by seroleanand** [paulcwarren/spring-content#700]
I am using MongoDB as a content store, Also I want to use s3 as a content store for another client.
But When I am trying to keep both dependencies (Mongo+ s3), the Application fails to boot.

error "required a bean of type 'DocumentContentStore' that could not be found."

Is there any way, I can keep multiple content stores and select one at the runtime?
So that I can easily switch my content store.

**Comment by paulcwarren** [comment]
Hi @seroleanand  - do you want to dynamically select at runtime?  Or do you just want to use one but select it when you start the application (for example)?

**Comment by seroleanand** [comment]
Hi @paulcwarren, I just want to use one but select it when I start the application.
Let's say, In my application.yml, I am having a property like 'content-store'.
if content-store: mongodb then documents should be uploaded/downloaded from mongodb and elastic search will index over mongodb.
if content-store: s3 then documents should be uploaded/downloaded from s3 and elastic search will index over s3.
Please let me know if this can be achieved with the latest release 1.2.6. Otherwise, I have to maintain 2 branches, one for mongo and other for s3 implementation.

**Comment by paulcwarren** [comment]
Hi @seroleanand, both are possible but the approach is different. 

For static store selection you can see this example [here](https://github.com/paulcwarren/multi-store-example/tree/fe4a1127425c14c045b4ed7c41ecb58007c102d9).  Specifically, see the [application.properties file](https://github.com/paulcwarren/multi-store-example/blob/fe4a1127425c14c045b4ed7c41ecb58007c102d9/src/main/resources/application.properties) in resources where the `spring.content.storage.override` property is set that selects the store to run the application with.

You can find the module ID in the documentation [here](https://paulcwarren.github.io/spring-content/refs/release/1.2.6/s3-index.html#_accessing_content) and [here](https://paulcwarren.github.io/spring-content/refs/release/1.2.6/mongo-index.html#_accessing_content).

**Comment by paulcwarren** [comment]
@seroleanand was this information and sample repository useful?

**Comment by seroleanand** [comment]
yes, @paulcwarren , It's working , Thanks for your quick help. Really appreciating.
