### ISSUE TITLE
logback-classic transitive dependency

### ISSUE THREAD

**Issue by janossch** [paulcwarren/spring-content#723]
Hi @andye2004 and @paulcwarren 

I've used spring content 1.2.2 version so far, and I've just updated to a newer version in our project, which includes the changes from this [Feature/PR](https://github.com/paulcwarren/spring-content/issues/541). 
Since then spring content directly depends on logback, so it appeared in our classpath, however our project isn't using logback but other SL4J implementation. I know it’s not a big deal, I can easily exclude the dependency out, but from such a nice framework, I would expect not force me to take such unnecessary steps.

So until now our pom.xml looked like this

```
<dependency>
 <groupId>com.github.paulcwarren</groupId>
 <artifactId>spring-content-fs-boot-starter</artifactId>
 <version>1.2.2</version>
</dependency>
```

If i would like to jump to the newer version I need the following _workaround_:
```
<dependency>
 <groupId>com.github.paulcwarren</groupId>
 <artifactId>spring-content-fs-boot-starter</artifactId>
 <version>1.2.6</version>
  <exclusions>
   <exclusion>
   <groupId>ch.qos.logback</groupId>
   <artifactId>logback-classic</artifactId>
   </exclusion>
   <exclusions>
</dependency>
```

I've just looked at the PR related to the above mentioned feature, but from that I feel the [test](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope) scope would meets the purpose, but that's just a guess.

What is your opinion?
Do you think I need to live together with the _dependency exclusion_? Or am i on a completely wrong track? :)

**Comment by paulcwarren** [comment]
Thanks for the report @janossch .   I think this was just an oversight on my part.  As a rule I havent put dependencies in the part pom.  I'll take a look at this for the next release.
