### ISSUE TITLE
Lombok dependency is exposed to consumers

### ISSUE THREAD

**Issue by vierbergenlars** [paulcwarren/spring-content#768]
**Describe the bug**

Some spring-content components have a dependency on lombok that is exposed to downstream consumers.

Since lombok is only used at compile-time to generate additional code and consumers do not have to care about this dependency, it should not be exposed downstream.

**To Reproduce**
1. Create a project with the spring-content-rest-boot-starter (but without lombok)
2. Add a class with a lombok-annotation to it.
3. Compile the project, notice that lombok is on the compile classpath and is unexpectedly run on my project.

**Expected behavior**

Lombok is not present on the compile- or runtime classpath of my application that uses spring-content.

**Additional context**

Snippet from the compile dependencies of my project, which depends on `spring-content-rest-boot-starter`
Note the indirect dependency on lombok, through the dependencies `spring-content-rest-boot-starter -> spring-content-rest -> spring-content-commons -> lombok`.

<details>
```
     +--- com.github.paulcwarren:spring-content-rest-boot-starter -> 1.2.7
     |    +--- com.github.paulcwarren:spring-content-rest:1.2.7
     |    |    +--- org.springframework:spring-webmvc:5.3.13 -> 5.3.15 (*)
     |    |    +--- javax.servlet:javax.servlet-api:4.0.1
     |    |    +--- org.springframework.hateoas:spring-hateoas:1.4.0 -> 1.4.1 (*)
     |    |    +--- org.springframework.data:spring-data-commons:2.6.0 -> 2.6.1 (*)
     |    |    +--- org.springframework.data:spring-data-rest-core:3.6.0 -> 3.6.1 (*)
     |    |    +--- com.github.paulcwarren:spring-content-commons:1.2.7
     |    |    |    +--- org.springframework:spring-context:5.3.13 -> 5.3.15 (*)
     |    |    |    +--- commons-io:commons-io:2.11.0
     |    |    |    +--- com.github.paulcwarren:spring-versions-commons:1.2.7
     |    |    |    |    +--- org.springframework.security:spring-security-core:5.6.0 -> 5.6.1
     |    |    |    |    |    +--- org.springframework.security:spring-security-crypto:5.6.1
     |    |    |    |    |    +--- org.springframework:spring-aop:5.3.14 -> 5.3.15 (*)
     |    |    |    |    |    +--- org.springframework:spring-beans:5.3.14 -> 5.3.15 (*)
     |    |    |    |    |    +--- org.springframework:spring-context:5.3.14 -> 5.3.15 (*)
     |    |    |    |    |    +--- org.springframework:spring-core:5.3.14 -> 5.3.15 (*)
     |    |    |    |    |    \--- org.springframework:spring-expression:5.3.14 -> 5.3.15 (*)
     |    |    |    |    +--- org.springframework.data:spring-data-commons:2.6.0 -> 2.6.1 (*)
     |    |    |    |    +--- org.springframework:spring-tx:5.3.13 -> 5.3.15 (*)
     |    |    |    |    \--- ch.qos.logback:logback-classic:1.2.9 -> 1.2.10 (*)
     |    |    |    +--- org.projectlombok:lombok:1.18.22
     |    |    |    \--- ch.qos.logback:logback-classic:1.2.9 -> 1.2.10 (*)
     |    |    +--- org.atteo:evo-inflector:1.3
     |    |    +--- com.github.paulcwarren:spring-versions-commons:1.2.7 (*)
     |    |    +--- org.springframework:spring-tx:5.3.13 -> 5.3.15 (*)
     |    |    +--- org.projectlombok:lombok:1.18.22
     |    |    \--- ch.qos.logback:logback-classic:1.2.9 -> 1.2.10 (*)
     |    +--- com.github.paulcwarren:spring-content-autoconfigure:1.2.7
     |    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.6.1 -> 2.6.3 (*)
     |    |    \--- ch.qos.logback:logback-classic:1.2.9 -> 1.2.10 (*)
     |    \--- ch.qos.logback:logback-classic:1.2.9 -> 1.2.10 (*)
```
</details>

I ran in to this issue because I am using Gradle for my spring-content project, where there is a separation between compile classpath and annotation-processors classpath. The lombok annotations did not result in an error during compilation because they were on the compile classpath, but the annotation processor did not run either, because lombok was not on the annotation-processor classpath.

**Comment by paulcwarren** [comment]
Thanks @vierbergenlarsm, since Spring Content is currently maven-based I am not sure what I can do about this.   

I suppose I can look into removing lombok from the classpath, leaving it on the test classpath since that is where is it mostly used.  Anyways, I will investigate and report back.

**Comment by paulcwarren** [comment]
Thanks Lars
