### ISSUE TITLE
Unset content on entity removal

### ISSUE THREAD

**Issue by pavlus** [paulcwarren/spring-content#77]
There is a case when entity that describes content is in relation with some other entity and is removed implicitly by cascade and not manually, so it may be necessary to register event listener to unset/delete content described by such entity.

Doing so manually requires boilerplate event listener each one of them injecting ContentStore for particular entity and doing same `store.unsetContent(entity)`.

Is there a way to reduce such boilerplate, mark entity/repository/store/etc aware of such events and do it automatically?

**Comment by paulcwarren** [comment]
Hi @pavlus,

This is a very good question.  There isn't anything at the moment I am afraid.

Can I ask how you achieving this at the moment?  With hibernate's `PreDeleteEventListener`?    Or something else?

**Comment by pavlus** [comment]
Hi, @paulcwarren I've tried few approaches: first described in initial post -- creating listener for each entity that has `@ContentId` manually, and setting hibernate's bean container to `SpringBeanContainer`.

 Second one was to create single listener service that autowires all content-repositories it should support and manually checking `instanceof` for each entity sent into it and selecting correct repository for each entity, which, I suppose, all are of the same implementation instance (I had to make quick and dirty GCP Storage integration, so made it from S3 variant). That was very dirty and I removed it and temporarely left records with content in DB, but unlinked.

Now I'm thinking that it may be ok to make repository implementation also listen for JPA events and delete content depending on some flag or switch in `@Content` annotation, like `unsetOnDelete=true`, or `onJpaDelete=UNSET/SET_NULL/DO_NOTHING`.

**Comment by paulcwarren** [comment]
Apologies for the tardy response times.  I have been at SpringOne and then catching up from SpringOne.

Let's say we have two entities, `A` and `B`.  `A` has a relationship to `B` and `B` is removed implicitly via cascade when `A` is deleted.  `B` has some content associated.

Would we need to add any flags?

Whatever event listener f/w you use - I was just reading about the [CDC f/w](https://vladmihalcea.com/hibernate-event-listeners/) - I think it would be possible to register a pre-delete event listener for the cascaded entity.  When called these are usually called with an event that gives you the entity.   So we have the entity and the entity's class to hand.
 
There is a bean in the spring-content sub-system called `ContentStoreService` that has a search method on it that would allow you to get the store from the entity class, like this:

```
ContentStoreInfo stores = contentStoreService.getStores(ContentStore.class, new StoreFilter() {
   if (entityClass.equals(info.getDomainObjectClass())) {
      return info;
   }
})
``` 

This returns an array but I presume it is safe to assume this would only ever return one store (do you have multiple stores per entity?).

With the store and the entity from the event you can then call `unsetContent`.

I believe this would be a reasonably generic, write once type of solution removing the boilerplate approach you mentioned originally.  

What do you think?

**Comment by paulcwarren** [comment]
Ping.  @pavlus.  Did this solution work for you?  Just curious.

**Comment by pavlus** [comment]
Hi, @paulcwarren , thanks and sorry for late response.

Yes, it worked, and here is how we implemented it:
```java
@Component
@RequiredArgsConstructor
@Slf4j
public class HibernateInterceptor extends EmptyInterceptor {

  private final ContentStoreService contentStoreService;

  @Override
  public void onDelete(Object entity, Serializable id, Object[] state, String[] propertyNames, Type[] types) {
    var stores = contentStoreService.getStores(ContentStore.class,
        info -> entity.getClass().equals(info.getDomainObjectClass()));

    Stream.of(stores)
        .map(storeInfo -> Optional.ofNullable(storeInfo.getImplementation(ContentStore.class)))
        .forEach(store -> store.ifPresentOrElse(
            s -> s.unsetContent(entity),
            () -> log.warn("ContentStore implementation not found for {}", entity.getClass())));

    super.onDelete(entity, id, state, propertyNames, types);
  }

}
```

**Comment by paulcwarren** [comment]
Thanks for getting back to me @pavlus.  Glad it worked for you.  Thanks for writing up your actual solution.  This will be useful for others.  Much appreciated.

I'm going to close this now but feel free to re-open if you would like.
