### ISSUE TITLE
StoreCandidateComponentProvider uses default environment in parent constructor

### ISSUE THREAD

**Issue by ramymagdy** [paulcwarren/spring-content#78]
The StoreCandidateComponentProvider uses the parent constructor ClassPathScanningCandidateComponentProvider(boolean useDefaultFilters) which uses a default empty environment.

Some of my ContentStores are actually annotated with @Profile, yet when evaluation these conditions, the activeProfiles are empty for the new empty environment, while they are set for the existing one, hence the evaluation fails and my ContentStores are not loaded.

That only happens when I declare my active profiles in the application.yml file, if I do set them through -Dspring.profiles.active, they do work just fine.

> ProfilesParser$ParsedProfiles.matches(Predicate<String>) line: 159	
StandardEnvironment(AbstractEnvironment).acceptsProfiles(Profiles) line: 346	
ProfileCondition.matches(ConditionContext, AnnotatedTypeMetadata) line: 39	
ConditionEvaluator.shouldSkip(AnnotatedTypeMetadata, ConfigurationCondition$ConfigurationPhase) line: 108	
ConditionEvaluator.shouldSkip(AnnotatedTypeMetadata, ConfigurationCondition$ConfigurationPhase) line: 90	
ConditionEvaluator.shouldSkip(AnnotatedTypeMetadata) line: 71	
StoreCandidateComponentProvider(ClassPathScanningCandidateComponentProvider).isConditionMatch(MetadataReader) line: 515	
StoreCandidateComponentProvider(ClassPathScanningCandidateComponentProvider).isCandidateComponent(MetadataReader) line: 498	
StoreCandidateComponentProvider(ClassPathScanningCandidateComponentProvider).scanCandidateComponents(String) line: 431	
StoreCandidateComponentProvider(ClassPathScanningCandidateComponentProvider).findCandidateComponents(String) line: 316	
StoreUtils.getStoreCandidates(ResourceLoader, String[], boolean, Class<?>[]) line: 67	
MongoContentAutoConfigureRegistrar.registerContentStoreBeanDefinitions(AnnotationMetadata, BeanDefinitionRegistry) line: 29	
MongoContentAutoConfigureRegistrar(AbstractStoreBeanDefinitionRegistrar).registerBeanDefinitions(AnnotationMetadata, BeanDefinitionRegistry) line: 129

**Comment by paulcwarren** [comment]
Hi @ramymagdy,

Thanks for raising this issue.  So, if I understand it.  To reproduce this issue:

### Steps:
1. Create a Spring Boot app
2. Create two ContentStore's.  One annotated with @Profile("foo") and the other with @Profile("bar")
3. Set `spring.profiles: foo` in the application.properties

### Expected results:
When the application is started we only expect one ContentStore to be loaded into the application context.

### Actual results:
Both ContetnStore's are loaded into the applicaiton context.

### Notes:
If I set the active profiles via `-Dspring.profiles.active=foo` then only one ContentStore is loaded, as expected.

**Comment by ramymagdy** [comment]
@paulcwarren 
In the actual case none of the content store get's loaded since in the default environment the spring active profiles are empty. only when setting -Dspring.profiles.active=foo a single content store gets loaded.

**Comment by paulcwarren** [comment]
OK.  Got it.  Thanks.  We'll investigate this.

**Comment by paulcwarren** [comment]
Fixed by [69ab4b3](https://github.com/paulcwarren/spring-content/commit/69ab4b3383f5da1954596a9271ca5052cede86d0) on master (0.x.0 codeline).

Fixed by [67e64bb](https://github.com/paulcwarren/spring-content/commit/67e64bbcfe7e927d918679e04b796aa873c3bd47) on 1.0.x.

**Comment by paulcwarren** [comment]
Let me know if this resolves the issue and I will cut releases.

**Comment by paulcwarren** [comment]
Let me know if this resolves the issue and I will cut releases.

**Comment by ramymagdy** [comment]
@paulcwarren I've tested it and the issue is indeed resolved. Thanks for your prompt response.

**Comment by paulcwarren** [comment]
Cool.  Will cut releases later on today.
