### ISSUE TITLE
Consider renaming modules (and projects?)

### ISSUE THREAD

**Issue by snicoll** [paulcwarren/spring-content#8]
As explained [in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) we'd like 3rd party starters not to use a `spring-` prefix to clearly separate 3rd party contributions from core support. 

Could you please consider renaming this project so that it does not start with  `spring-*`?

**Comment by paulcwarren** [comment]
We are not adding auto-configuration for a third party system, rather we are adding a capability to Spring itself for handling content/resources comprising a "Store" abstraction for storing content in a variety of different types of store, versioning content, searching "inside" content, rendering from one format to another, etc.  This (hopefully) makes it a lot easier to write that class of solution that has to manage files, images, video, etc.  Basically it is to "files" what Spring Data is to structured data.  So in this regard I think the naming `spring-content-(jpa|mongo|s3|fs|rest)-boot-starter` makes sense.  This would also constitute a breaking change for our users as we would need to change the maven coordinates.  I don't know if these aspects change your requirement at all?

**Comment by snicoll** [comment]
Sorry but it does not. The intent of the doc is to separate official starters from third party contributions (nothing to do with third party system, really).

**Comment by paulcwarren** [comment]
I didn't think it would but had to ask.  Should have RTFMed before creating those projects in the first place.  I'll discuss renaming them here.  Thanks.

**Comment by paulcwarren** [comment]
Renamed in 0.0.6 release.  Will update my PR branch and re-submit.
