### ISSUE TITLE
Fulltext Indexing can't index words in images 

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#80]
please provide  a call back interface before ElasticsearchIndexer process,which can intervene image full text

**Comment by paulcwarren** [comment]
I dont believe that elasticsearch has OCR.  They deem it to memory intensive and a potential bottleneck for the nodes.  Is that your understanding too?  

Can we explore your intentions further?   Is your plan to try and plug some "ocr" solution into your spring-content application?  So that, perhaps, when content is added with an image mime-type it is run through your ocr and the extracted text is then sent to elasticsearch to be added to its index?

**Comment by lmtoo** [comment]
yes , add a Resource to text Converter should be more flexible , then converted text sent to elasticsearch

**Comment by paulcwarren** [comment]
Hi @lmtoo,

Given that `spring-content-renditions` is all about transforming content from one format into another.  And ocr is essentially about transforming images into text I am thinking about using the Renditions Service to power this additional functionality and wanted to run it past you to see what you think.

So the basic plan would be to add one or more `image/*` to `text/plain` renderers via configuration.  Something like this:

```
    @Bean
    public RenditionProvider resourceConverter() {
        return new RenditionProvider() {

            @Override
            public String consumes() {
                return "image/png";
            }

            @Override
            public String[] produces() {
                return new String[] {"text/plain"};
            }

            @Override
            public InputStream convert(InputStream fromInputSource, String toMimeType) {
                tesseract.TessBaseAPI api = new tesseract.TessBaseAPI();

                if (api.Init("/Users/warrep/workspace/tessdata", "eng") != 0) {
                   ...
                }

                // Open input image with leptonica library
                byte[] bytes = new byte[0];
                try {
                    bytes = IOUtils.toByteArray(fromInputSource);
                }
                catch (IOException e) {
                   ...
                }
                lept.PIX pix = pixReadMem(bytes, bytes.length);
                api.SetImage(pix);

                BytePointer outText = api.GetUTF8Text();

                String txt = outText.getString();

                api.End();
                outText.deallocate();
                pixDestroy(pix);

                return new ByteArrayInputStream(txt.getBytes());
            }
        };
    }
```

We could have out of the box renderers eventually but this approach would allow Developers to add the ocr package they need to use.

The `ElasticsearchIndexer` would then be updated to check if there is a renderer configured to convert from the content's mimetype to `text/plain.  If so, it would call it and send the resulting text to elasticsearch.

The implications of this approach (that I can think of) are:
- renderers would be configured and therefore these renditions would be available via the store/REST APIs.  That said, the store would have to extend `Renderable` and if does then presumably the Developer intends for renditions, including image to text, to be available.

Questions:
- renderers are configured globally, as is the elasticsearch integration, and therefore ocr would happen for all stores.  does that work for your use case?  do you have more than one entity with content?

**Comment by lmtoo** [comment]
so far, I only have One entity with content, but ,Index depends on the entity status，also ，search  involve current user's authorities, different user search different results.

Fulltext Indexing can annotated on Entity Class? 

original content is never sent to elasticsearch would work fine for my use case.

**Comment by lmtoo** [comment]
Any plans in the near future to release a new version? I can't wait to use Spring HATEOAS 1.0.0 RELEASE and Spring Boot 2.2.1 RELEASE

**Comment by paulcwarren** [comment]
Thanks for the info re. the use case.

We are maintaining two release trains atm; 0.x.0 and 1.0.0.Mx.  1.0.0.M3 supports Spring Boot 2.2.x and HATEOAS 1.  This is tested against milestone releases atm but I suspect should work against the final releases.  Have you found this release not to work?  ltk

**Comment by paulcwarren** [comment]
The ability to configure elasticsearch to perform text extraction via one or more renderers is now available via SNAPSHOT.  Docs have been updated too.

Closing.  Feel free to re-open if you have any issues.
