### ISSUE TITLE
wrong field spell in LockingAndVersioningRepository.findAllVersions's @Query value

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#83]
`@Query("select t from #{#entityName} t where t.ancestralRootId = ?#{#entity.ancestralRootId}")
    <S extends T> List<S> findAllVersions(@Param("entity") S entity);`
the ancestralRootId is't consistent with @AncestorRootId annotation

**Comment by paulcwarren** [comment]
Agreed.  In reality, we shouldn't be hardcoding the query and take a more programmatic approach where we can detect the name of the fields by finding them by annotation.

Will fix.

**Comment by paulcwarren** [comment]
Fixed in [this commit](https://github.com/paulcwarren/spring-content/commit/5785817ee9e16f6132888049e63cfe1afba811c5)
