### ISSUE TITLE
Consider add HttpServletRequest to InputStream or Resource converter in ContentEntityRestController

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#85]
ContentEntityRestController direct get InputStream from HttpServletRequest ,but I recently meet a requirements that through form submit a file id or url to do the upload,
add a HttpServletRequest to InputStream or Resource converter should be more flexible,
also domainObj as the Converter's second parameter should be more flexible,

**Comment by paulcwarren** [comment]
I am not sure I fully understand your use case.  can you explain further?   Do you have an HTML form that will submit the id or URL of a file that the controller would then need to fetch and use as content?  

Also, as we speak, we are refactoring our controller implementations into `HandlerMethodArgumentResolver`'s that will resolve request mappings into a Resource (and various associated arguments).  This is 70% completed and I anticipate a commit next week sometime.  Perhaps you could take a look at that and see if it resolves your issue - although I don't think so.

**Comment by lmtoo** [comment]
HandlerMethodArgumentResolver is work for me , thanks

**Comment by lmtoo** [comment]
HandlerMethodArgumentResolver only support ContentStore's Resource ?  
My problem is content maybe a multipart-data , or content may resolved by a paramter

**Comment by paulcwarren** [comment]
So, you are talking about getting access to the http request in StoreEventHandler's method - like in the afterSetContent event for example, or in Renderer's, or both @lmtoo?

**Comment by paulcwarren** [comment]
@lmtoo ping.  does the above solve your problem?   and in a clean way?

**Comment by lmtoo** [comment]
ok
