### ISSUE TITLE
spring.content.rest.base-uri leading slash missing

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#87]
I configed spring.content.rest.base-uri=/api/v1 ,but result document link is 

`http://localhost:8080/archivesapi/v1/content/4`

 compile group: 'com.github.paulcwarren', name: 'spring-content-rest-boot-starter', version: '1.0.0.M3'

**Comment by paulcwarren** [comment]
I am unable to reproduce this @lmtoo

In a spring boot application, I have this dependency:

```
		<dependency>
			<groupId>com.github.paulcwarren</groupId>
			<artifactId>spring-content-rest-boot-starter</artifactId>
			<version>1.0.0.M3</version>
		</dependency>
``` 

and this is my application.properties:

`spring.content.rest.base-uri=/api/v1`

I also tried:

`spring.content.rest.baseUri=/api/v1`

And I was able to post content for a document to:

```
Request URL: http://localhost:9090/api/v1/documentscontent/ec39165b-ddd8-4cba-b3d4-dab846a39291
Request Method: POST
Status Code: 201 
Remote Address: [::1]:9090
Referrer Policy: no-referrer-when-downgrade
```

Is it possible to create a small spring boot app that repro-es the issue, push it to your github org and point this issue at it?

**Comment by lmtoo** [comment]
ok , the address is [](https://github.com/lmtoo/spring-content-demos)

**Comment by lmtoo** [comment]
https://github.com/lmtoo/spring-content-demos

**Comment by paulcwarren** [comment]
@lmtoo,

[This line](https://github.com/lmtoo/spring-content-demos/blob/cea40431636cf0d0b45936e60981c6fb98a6189a/src/main/java/cn/lmtoo/demo/springcontent/DocumentContentStore.java#L9) will mean that document content is exported to `/archives/api/v1/content`, not `/archives/api/v1/documents`.

That said, there is a bug in the refactored rest API that can't handle context paths by the looks, in this case "/archives".  Will look into this.
