### ISSUE TITLE
failing build on openjdk 12

### ISSUE THREAD

**Issue by Zavael** [paulcwarren/spring-content#88]
I tried to build `master` branch, I used commands `BUILD_TYPE=dev ./mvnw clean package` and `BUILD_TYPE=dev mvn clean package` but the build is failing on project `spring-content-autoconfigure` with error stacktrace:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spring-content-autoconfigure: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project spring-content-autoconfigure: Fatal error compiling
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
...
Caused by: java.lang.NullPointerException
    at com.sun.tools.javac.main.JavaCompiler.readSourceFile (JavaCompiler.java:841)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete (JavacProcessingEnvironment.java:1526)
```

my java version:
```
$ java -version
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+32)
OpenJDK 64-Bit Server VM (build 12+32, mixed mode, sharing)
```

maven version
```
$ mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: C:\Program Files\Apache Software Foundation\apache-maven-3.6.1
Java version: 12, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-12
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

does anyone have the same issue?

**Comment by paulcwarren** [comment]
@Zavael we only use JDK 8 atm.  I am not sure what the standard Spring libraries do in this regard actually.  Its a good question.  I suspect they have builds against a range of JDKs.  

I updated travis to build against 8, 10, 11 and 12.  Results [here](https://travis-ci.org/paulcwarren/spring-content/builds/615532878).  10, 11 and 12 all failed but for different reasons:

- openjdk10; failed because of a [jacoco issue](https://travis-ci.org/paulcwarren/spring-content/jobs/615532880#L5040) which looks to be open issue but raised against [openjdk13](https://github.com/jacoco/jacoco/issues/828).  

- openjdk11 & 12 (`build 12.0.2+10`); failed because of a missing [javax.activation package](https://travis-ci.org/paulcwarren/spring-content/jobs/615532881#L3373)

So, not the error you saw which is a little bit curious.  Did you not see the missing `javax.activation` package?

**Comment by Zavael** [comment]
Oh at least I am not alone. For now, downgrading to jdk8..
Unfortunately, I am not familiar with travis (seems like a tool good to learn), but after setting `source` and `target` in maven compiler plugin to `12` instead of former `1.8` the exception is a little more verbose (all other remains the same, java, maven and spring-content-autoconfigure as the source of failure):
```
...
constituent[40]: file:/C:/Users/xz/.m2/wrapper/dists/apache-maven-3.5.2-bin/7hf0mht29afbpa1e4v2d1a16p0/apache-maven-3.5.2/lib/wagon-file-2.12.jar
constituent[41]: file:/C:/Users/xz/.m2/wrapper/dists/apache-maven-3.5.2-bin/7hf0mht29afbpa1e4v2d1a16p0/apache-maven-3.5.2/lib/wagon-http-2.12-shaded.jar
constituent[42]: file:/C:/Users/xz/.m2/wrapper/dists/apache-maven-3.5.2-bin/7hf0mht29afbpa1e4v2d1a16p0/apache-maven-3.5.2/lib/wagon-provider-api-2.12.jar
---------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)
Caused by: java.lang.AssertionError
        at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
...
```
here is the full [pastebin output](https://pastebin.com/G7NFvAAM)
I had no problem of building `spring-content-rest` project.
its frustrating that the stacktrace contains only jdk paths and nothing useful to repair :( but it seems its not the problem of spring-content after all, so you can close this issue

**Comment by paulcwarren** [comment]
Closing as per comment.

**Comment by Godin** [comment]
> openjdk10; failed because of a jacoco issue which looks to be open issue but raised against openjdk13.

@paulcwarren https://github.com/jacoco/jacoco/issues/828 is not at all about JaCoCo compatibility with Java versions.

Support for Java 10 was added in JaCoCo version `0.8.1` - see https://github.com/jacoco/jacoco/pull/629 whose description contains exactly the same stacktrace as in your failing build with JDK 10. Furthermore  official support for Java 11 and experimental for Java 13 was added in `0.8.3`, official for Java 12 in `0.8.4`, and official for Java 13 in `0.8.5` - see https://www.jacoco.org/jacoco/trunk/doc/changes.html

And [you currently use JaCoCo version `0.7.8`](https://github.com/paulcwarren/spring-content/blob/bf7a23ad399c1d4d9906b66e7774f757463205c5/pom.xml#L152), so here is PR with upgrade - https://github.com/paulcwarren/spring-content/pull/91
