### ISSUE TITLE
Change ContentStore save directory

### ISSUE THREAD

**Issue by estebes** [paulcwarren/spring-content#9]
How do i change the default directory where the ContentStore stores its contents? I've tried adding spring.content.fs.filesystemRoot=mypath to the application.properties file but nothing happens. And if it is possible i would like to remove the random naming the scheme so i can use the same directories after restarting the server

**Comment by paulcwarren** [comment]
If using 0.0.5 you can add the following sort of configuration to your config:-

```
    @Bean
    File filesystemRoot() {
        try {
            return Files.createTempDirectory("").toFile();
        } catch (IOException ioe) {}
        return null;
    }

    @Bean
    FileSystemResourceLoader fileSystemResourceLoader() {
        return new FileSystemResourceLoader(filesystemRoot().getAbsolutePath());
    }
```

This configuration, from one of our example projects, shows that in a little more detail https://github.com/paulcwarren/spring-content-examples/blob/master/spring-eg-content-fs/src/test/java/examples/EnableFilesystemStoresConfig.java

Let me know if you need any more help.

**Comment by estebes** [comment]
This worked perfectly. Thank you very much.

**Comment by estebes** [comment]
New problem came up. Considering i'm storing videos in the server and providing them to the client-side is there anything special needed to make the store support byte ranges? It is the only thing not working for me at the moment.

**Comment by paulcwarren** [comment]
The Spring Content REST module adds byte range support to stores.  Are you using that and it is not working?  If you are then we take a closer look at that.  If you are not then you should just need to add `spring-content-rest-boot-starter` to your dependencies and the video stream will be available through the relevant endpoint; e.g. if your store is as follows:-

```
public interface VideoStore implements ContentStore<Video, UUID> {}
```

Then video streams will be available at `/videos/{uuid}`.  

The Spring Content REST docs are [here](https://paulcwarren.github.io/spring-content/refs/release/rest-index.html).  

You can also see an example of video streaming in a recent demo project we produced [here](https://github.com/paulcwarren/springflix).

And in case it is useful we test our byte range support [here](https://github.com/paulcwarren/spring-content/blob/master/spring-content-rest/src/test/java/internal/org/springframework/content/rest/controllers/ContentEntityRestControllerIntegrationTest.java#L208) 

Anyway, let us know if you are already using the Spring Content REST module or not and we can take it from there.

**Comment by estebes** [comment]
Yes. Been added to the project since i started using Spring Content. Also ContentStoreRestResource is deprecated so i assume i should use StoreRestResource.

**Comment by estebes** [comment]
Thanks a lot for the help. Managed to get it to work. One question i do have is if there is something similar to  spring.data.rest.base-path=/api or if this is value is also used in Spring Content.

**Comment by paulcwarren** [comment]
> Also ContentStoreRestResource is deprecated so i assume i should use StoreRestResource.
Yes, that's correct.  In general we are moving towards a more general API.  Just to be clear ContentStore isn't going away though.

> One question i do have is if there is something similar to spring.data.rest.base-path=/api or if this is value is also used in Spring Content.
We don't support this yet.  If you require it, happy to add it to the next release though.  0.0.6 is almost baked so it would make it into in 0.0.7

**Comment by estebes** [comment]
I think it is a good addition since it provides better compatibility between rest repositories and content stores. Everything is working now and i am really thankful for the help. Keep up the awesome work.

**Comment by paulcwarren** [comment]
On the manifest for 0.0.7.   Thanks @estebes

**Comment by estebes** [comment]
Hey! Another thing popped up. If i have getters in an entity that don't have associated fields (i.e public boolean getActive() {return true;} instead of having a field called active and returning it) the server console gets spammed with warning errors - WARN 20736 --- [nio-8080-exec-1] .o.s.c.r.l.ContentLinksResourceProcessor : Unexpected error handling content links for property something. Is there a way to avoid this without having to implement every single field? Also happens if the field is from a mapped superclass.

**Comment by paulcwarren** [comment]
That sounds like a bug @estebes.  We will investigate.

**Comment by paulcwarren** [comment]
Missing field getter problem fixed in [this build](https://travis-ci.org/paulcwarren/spring-content/builds/272289422).

Thanks for reporting.

**Comment by estebes** [comment]
Hi once again. This time i bring you a request. Could you guys add a PATCH method support to the stores? Rest repositories already support this and it is much cleaner way of updating some misc fields of a resource than using the PUT method. Thanks in advance.

**Comment by paulcwarren** [comment]
Hi @estebes, thanks for the FR.  So if I understand you you would like PATCH to support so that you can update part of a content object.  Is that correct?

**Comment by estebes** [comment]
Exactly. It helps a lot when you want to just update something like the resource description or title without having to send every single field again and again.

**Comment by paulcwarren** [comment]
Great.  just wanted to make sure I understood.  Yeah, PATCH on the backlog anyway so we'll bump its priority and see if we can get it done for 0.0.7 for you.

**Comment by estebes** [comment]
You guys are amazing. Thank you very much.
