### ISSUE TITLE
BeforeSetContentEvent couldn't access the content

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#93]
hi, @paulcwarren ,I recently met a requirements, to restrict the content's MediaType, like only PDF file upload is supported and  calculate total pages of the PDF before persist ,but BeforeSetContentEvent  doesn't support to access the content's inputStream, BeforeSetContentEvent could support these in future version?

**Comment by paulcwarren** [comment]
I believe someone else asked for this same thing @lmtoo.  We just need to figure out "how" to make the stream reliably available to the beforesetcontentevent and then again to the actual set content operation.

**Comment by paulcwarren** [comment]
Fixed with [this commit](https://github.com/paulcwarren/spring-content/commit/3f4af6c16f4a31a05c94229c0c55b81a224346d8)
